### ISSUE TITLE
Spawn in a basic_executor

### ISSUE THREAD

**Issue by samanpa** [tokio-rs/tokio#2526] opened 2020-05-12 12:14 UTC
## Version
0.2.20

## Platform
3.10.0-1062.7.1.el7.x86_64 #1 SMP Wed Nov 13 08:44:42 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description
The following code doesn't print spawn with the `basic_executor` but works as expected with the `threaded_executor`
```rust
fn main() {
    let mut rt = tokio::runtime::Builder::new()
        .basic_scheduler()
        .build()
        .unwrap();

    rt.handle().spawn( async {
        println!("spawn")
    });

    rt.block_on(async {
        println!("block on");
    });
}
```

**Comment by Darksonn** [comment] 2020-05-12 12:24
This is because the `block_on` async block has no `.await`, so it never yields back to the executor before it finishes, and when it finishes, the `block_on` method returns immediately. This means that the spawned future never got a moment to run, because the basic scheduler only runs spawned futures inside calls to `block_on`.

If you yield inside the blocked-on future, you will see that it does print "spawn".
```rust
fn main() {
    let mut rt = tokio::runtime::Builder::new()
        .basic_scheduler()
        .build()
        .unwrap();

    rt.handle().spawn( async {
        println!("spawn")
    });

    rt.block_on(async {
        println!("block on a");
        tokio::task::yield_now().await; // prints spawn here
        println!("block on b");
    });
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e1ecef5a46a34755397fe04104ef455)

The threaded executor works very differently, and the spawned future would run on a different thread than the blocked-on future. In principle it is not guaranteed that the spawned future would get executed, e.g. if the runtime object gets dropped before a worker thread gets around to starting the spawned future, which would cause the spawned future to be cancelled, but that would require some very unlikely timing.

This is expected behavior, so I am closing the issue. You should still feel free to ask additional questions on the issue.

**Closed by Darksonn** 2020-05-12 12:24 UTC
Labels: A-tokio, C-question, M-runtime

**Comment by samanpa** [comment] 2020-05-12 13:07
This is a reduced example. Ideally I wanted the user to supply their own runtime for work to be done on.
I would argue that the basic_executor should panic if it is not going to support spawning.

**Comment by Darksonn** [comment] 2020-05-12 13:09
The basic executor does support spawning, but spawned futures are only executed during calls to `block_on`.
