### ISSUE TITLE
Awaiting on WatchStream channel gets output twice

### ISSUE THREAD

**Issue by reza-ebrahimi** [tokio-rs/tokio#3655] opened 2021-03-27 12:57 UTC
**Version**
```
[dependencies]
tokio = { version = "1.1.0", features = ["full"] }
tokio-stream = { version = "0.1.5", features = ["sync"] }
```

**Platform**
```
$ uname -a
Linux dev 5.4.0-67-generic #75~18.04.1-Ubuntu SMP Tue Feb 23 19:17:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**
Awaiting on WatchStream in a loop, will get the last value twice, While were sending once.

Testcode:

```rust
#[tokio::main]
async fn main() {
    let (tx, rx) = watch::channel("hello");

    let mut stream = WatchStream::new(rx).map(|payload| {
        println!("{}", payload);
    });

    let task = tokio::spawn(async move {
        loop {
          stream.next().await;
        }
    });

    // Send goodbye just once
    tx.send("goodbye").unwrap();

    task.await.ok();
}
```

Output:

```console
goodbye
goodbye
```

**Comment by Darksonn** [comment] 2021-03-27 13:29
I don't think this can be fixed without exposing new methods on the watch receiver in Tokio. E.g. we might expose a `version` method. This would involve changing `send` to increment version before the write lock is released, as it is otherwise not possible to reliably get the current version of the value returned by `borrow()`. We could also add a method similar to `changed()` that returns a reference to the actual value.

Thoughts @carllerche ?

**Comment by teozkr** [comment] 2021-06-04 10:23
This seems to be a regression between tokio-stream 0.1.3 and 0.1.4, FWIW.

**Closed** 2021-07-02 21:24 UTC
Labels: A-tokio, C-bug, M-sync
