### ISSUE TITLE
Calling `yield_now` (twice) causes `Delay` to complete when `time` is paused in test

### ISSUE THREAD

**Issue by mariusmuja** [tokio-rs/tokio#2090] opened 2020-01-10 19:05 UTC
## Version

 `> 0.2.6`. Does not occur in `0.2.6`.

## Platform
Linux atwell 5.0.0-35-generic #38-Ubuntu SMP Sat Nov 9 17:51:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description

Test code:
```rust
#[tokio::test]
async fn test_timer() {

    time::pause();

    let mut delay = delay_for(Duration::from_secs(1));

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    tokio::task::yield_now().await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    tokio::task::yield_now().await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    time::advance(Duration::from_secs(2)).await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Ready(()));
}
```

Output in 0.2.6:
```
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 1001, waker: AtomicWaker, queued: true, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 1001, waker: AtomicWaker, queued: false, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 1001, waker: AtomicWaker, queued: false, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 9223372036854776809, waker: AtomicWaker, queued: false, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
test session::tests::test_timer ... ok
```

Output in 0.2.9:
```
running 1 test
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 1001, waker: AtomicWaker, queued: true, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 1001, waker: AtomicWaker, queued: false, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
Delay { registration: Registration { entry: Entry { time: CachePadded(UnsafeCell), inner: (Weak), state: 9223372036854776809, waker: AtomicWaker, queued: false, next_atomic: UnsafeCell, when: UnsafeCell, next_stack: UnsafeCell, prev_stack: UnsafeCell } } }
thread 'session::tests::test_timer' panicked at 'assertion failed: `(left == right)`
  left: `Ready(())`,
 right: `Pending`', 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test session::tests::test_timer ... FAILED
```

**Comment by udoprog** [comment] 2020-01-13 13:52
Hey, which implementation of the `poll!` macro are you using?

**Comment by mariusmuja** [comment] 2020-01-13 16:34
I'm using `futures::poll` (from `futures-0.3.1`).

**Comment by seanmonstar** [comment] 2020-01-14 20:59
This is https://github.com/tokio-rs/tokio/issues/1897

**Comment by rimmartin** [comment] 2020-01-28 15:11
@mariusmuja Hi, flann needs some attention

**Comment by tesaguri** [comment] 2021-08-10 03:31
The test passes starting from [Tokio v1.6.2] release.

[Tokio v1.6.2]: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.6.2

I've updated the test to work with Tokio v1 as follows, but this should be essentially the same as OP's code.

```rust
use std::task::Poll;
use std::time::Duration;

use futures_util::poll;
use tokio::{pin, time};

#[tokio::test]
async fn test_timer() {
    time::pause();

    let delay = time::sleep(Duration::from_secs(1));
    pin!(delay);

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    tokio::task::yield_now().await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    tokio::task::yield_now().await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Pending);

    time::advance(Duration::from_secs(2)).await;

    let res = poll!(&mut delay);
    println!("{:?}", delay);
    assert_eq!(res, Poll::Ready(()));
}
```

[Playground]

[Playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5a6ff3d3e8277ce95396631bb4baa7ea

**Comment by Darksonn** [comment] 2021-08-10 06:10
@tesaguri So what you're saying is that this can be closed?

**Comment by tesaguri** [comment] 2021-08-10 09:21
> @tesaguri So what you're saying is that this can be closed?

I don't know the root cause of the issue so I'm not 100% sure,  but yes, I suppose closing the issue is OK. My code that seemed to be affected by the issue works fine now, at least.

**Closed** 2021-08-10 09:25 UTC
Labels: C-bug, A-tokio, M-time
