### ISSUE TITLE
hammer_split test: 'tokio-runtime-worker-0' panicked at 'connect error = Os

### ISSUE THREAD

**Issue by minamonk** [tokio-rs/tokio#742] opened 2018-11-07 08:32 UTC
## Version

0.1.12

## Platform

Darwin mini.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

## Description

Enter your issue details below this comment.

I ran:

`cargo test`

I expected the tests to run and pass.

Instead, this happened:
`thread 'tokio-runtime-worker-0' panicked at 'connect error = Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', tests/global.rs:128:39
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:345
   7: global::hammer_split::{{closure}}
             at tests/global.rs:128
   8: <core::result::Result<T, E>>::map_err
             at libcore/result.rs:530
   9: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:34
  10: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map.rs:30
  11: core::num::<impl usize>::max_value
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  12: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  13: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  14: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  15: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  16: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  17: <tokio_threadpool::callback::Callback as core::clone::Clone>::clone
             at /Users/research/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  18: tokio_threadpool::task::Task::run::{{closure}}
             at tokio-threadpool/src/task/mod.rs:127
  19: core::ops::function::FnOnce::call_once
             at libcore/ops/function.rs:238
  20: <usize as core::ops::arith::Sub>::sub
             at libstd/panic.rs:313
  21: tokio_threadpool::shutdown_task::ShutdownTask::notify
             at libstd/panicking.rs:310
  22: panic_unwind::imp::find_eh_action::{{closure}}
             at libpanic_unwind/lib.rs:102
  23: tokio_threadpool::shutdown_task::ShutdownTask::notify
             at libstd/panicking.rs:289
  24: <usize as core::ops::arith::Sub>::sub
             at libstd/panic.rs:392
  25: tokio_threadpool::task::Task::run
             at tokio-threadpool/src/task/mod.rs:113
  26: tokio_threadpool::worker::Worker::run_task2
             at tokio-threadpool/src/worker/mod.rs:550
  27: tokio_threadpool::worker::Worker::run_task
             at tokio-threadpool/src/worker/mod.rs:451
  28: tokio_threadpool::worker::Worker::try_run_owned_task
             at tokio-threadpool/src/worker/mod.rs:391
  29: tokio_threadpool::worker::Worker::try_run_task
             at tokio-threadpool/src/worker/mod.rs:299
  30: tokio_threadpool::worker::Worker::do_run
             at tokio-threadpool/src/worker/mod.rs:240
  31: tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/runtime/builder.rs:283
  32: core::cmp::impls::<impl core::cmp::PartialOrd for u64>::partial_cmp
             at ./tokio-timer/src/timer/handle.rs:94
  33: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:300
  34: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:254
  35: core::cmp::impls::<impl core::cmp::PartialOrd for u64>::partial_cmp
             at ./tokio-timer/src/timer/handle.rs:81
  36: tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at src/runtime/builder.rs:282
  37: <std::time::Instant as core::cmp::PartialOrd>::gt
             at ./tokio-timer/src/clock/clock.rs:136
  38: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:300
  39: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:254
  40: <std::time::Instant as core::cmp::PartialOrd>::gt
             at ./tokio-timer/src/clock/clock.rs:119
  41: tokio::runtime::builder::Builder::build::{{closure}}::{{closure}}
             at src/runtime/builder.rs:281
  42: <core::time::Duration as core::cmp::PartialOrd>::le
             at ./tokio-reactor/src/lib.rs:229
  43: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:300
  44: core::ptr::swap_nonoverlapping_bytes
             at libstd/thread/local.rs:254
  45: <core::time::Duration as core::cmp::PartialOrd>::le
             at ./tokio-reactor/src/lib.rs:212
  46: tokio::runtime::builder::Builder::build::{{closure}}
             at src/runtime/builder.rs:280
  47: tokio_threadpool::callback::Callback::call
             at tokio-threadpool/src/callback.rs:21
  48: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at tokio-threadpool/src/worker/mod.rs:122
  49: <std::time::Instant as core::cmp::PartialOrd>::lt
             at ./tokio-executor/src/global.rs:192
  50: core::cmp::impls::<impl core::cmp::PartialOrd for usize>::lt
             at libstd/thread/local.rs:300
  51: core::cmp::impls::<impl core::cmp::PartialOrd for usize>::lt
             at libstd/thread/local.rs:254
  52: <std::time::Instant as core::cmp::PartialOrd>::lt
             at ./tokio-executor/src/global.rs:162
  53: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at tokio-threadpool/src/worker/mod.rs:120
  54: core::cmp::impls::<impl core::cmp::PartialOrd for usize>::lt
             at libstd/thread/local.rs:300
  55: core::cmp::impls::<impl core::cmp::PartialOrd for usize>::lt
             at libstd/thread/local.rs:254
  56: tokio_threadpool::worker::Worker::do_run
             at tokio-threadpool/src/worker/mod.rs:111
  57: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at tokio-threadpool/src/pool/mod.rs:423
  58: <alloc::string::String as core::ops::deref::Deref>::deref
             at libstd/sys_common/backtrace.rs:136
  59: tokio_threadpool::worker::Worker::with_current::{{closure}}
             at libstd/thread/mod.rs:409
  60: <usize as core::ops::arith::Sub>::sub
             at libstd/panic.rs:313
  61: tokio_threadpool::shutdown_task::ShutdownTask::notify
             at libstd/panicking.rs:310
  62: panic_unwind::imp::find_eh_action::{{closure}}
             at libpanic_unwind/lib.rs:102
  63: tokio_threadpool::shutdown_task::ShutdownTask::notify
             at libstd/panicking.rs:289
  64: <usize as core::ops::arith::Sub>::sub
             at libstd/panic.rs:392
  65: tokio_threadpool::worker::Worker::with_current::{{closure}}
             at libstd/thread/mod.rs:408
  66: tokio_threadpool::worker::Worker::with_current::{{closure}}
             at liballoc/boxed.rs:672
  67: std::sys_common::thread::start_thread
             at liballoc/boxed.rs:682
             at libstd/sys_common/thread.rs:24
  68: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  69: _pthread_body
  70: _pthread_start`

**Comment by tobz** [comment] 2018-11-07 14:14
What's happening in your code around `tests/global.rs:128`?  It looks like your code is panicking and it's bubbling up through the Tokio worker thread.  That doesn't strike me as a Tokio problem at all, but it's hard to say definitively without seeing a little more of the code.

**Comment by tobz** [comment] 2018-11-07 17:51
Oops, sorry! I just realized this is actually a Tokio test. 😜 

0.1.12 was yanked due to some breakage, so I'm going to close this.  If you see this with 0.1.11 or newer versions, definitely let us know!

**Comment by minamonk** [comment] 2018-11-08 05:16
This is the tokio i literally "git cloned" yesterday, so I'm guessing it is the newer version

**Comment by tobz** [comment] 2018-11-08 14:02
Ah, interesting!

I have macOS, so I'll see if I can replicate the same errors.  Were you getting them consistently?

**Comment by carllerche** [comment] 2018-11-20 06:10
Does it happen reliably? I have been unable to reproduce.

**Comment by carllerche** [comment] 2019-01-30 21:59
Closing due to inactivity and the inability to reproduce.

It sounds like an OS limit is being hit during the benchmark.

**Closed by carllerche** 2019-01-30 21:59 UTC
Labels: incomplete
