### ISSUE TITLE
SendHalf for UDP socket should support ToSocketAddrs

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#1877] opened 2019-12-01 09:23 UTC
## Version

tokio v0.2.2

## Platform

Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

## Subcrates

net

## Description

```rust
impl SendHalf {
    pub async fn send_to<A: ToSocketAddrs>(&mut self, buf: &[u8], target: A) -> io::Result<usize>;
}
```

**Comment by Darksonn** [comment] 2020-07-25 08:48
Closing as duplicate of #2694.

**Closed by Darksonn** 2020-07-25 08:48 UTC
Labels: A-tokio, C-enhancement, M-net
