### ISSUE TITLE
Panicking inside `block_on` future allows uncooperative task to prevent shutdown

### ISSUE THREAD

**Issue by SergioBenitez** [tokio-rs/tokio#4780] opened 2022-06-21 06:37 UTC
**Version**

tokio v1.19.2

**Platform**

macOS 12.4

**Description**

As the title suggests, if a task is spawned that blocks indefinitely _and_ the future passed to `block_on()` panics, the runtime fails to shutdown. Here's a complete example that illustrates the problem:

```rust
fn main() {
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("Failed building the Runtime");

    println!("Starting async work.");

    runtime.block_on(async {
        println!("Starting infinite, uncooperative task...");
        tokio::spawn(async {
            loop {}
        });

        panic!("Done.");
    });

    println!("Returned from block_on(). Shutting down now.");
    runtime.shutdown_background();
    println!("Shut down. Exiting.");
}
```

Running the above program as-is results in:

```sh
> cargo run
Starting async work.
Starting infinite, uncooperative task...
thread 'main' panicked at 'Done.', src/main.rs:48:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# ... process never terminates ...
```

If we remove _only_ the panic (or both the panic and the infinite loop), we get:

```sh
> cargo run
Starting async work.
Starting infinite, uncooperative task...
Returned from block_on(). Shutting down now.
Shut down. Exiting.
# process terminated
```

If we remove _only_ the infinite loop we get:

```sh
> cargo run
Starting async work.
Starting infinite, uncooperative task...
thread 'main' panicked at 'Done.', src/main.rs:48:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
# process terminated
```

This behavior contradicts several pieces of documentation. Namely that of:
  * [`block_on`](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on), which says that the method panics if the provided future panics, but here the futures panics but `block_on` doesn't, or else the program would terminate
  *  [`shutdown_background`](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.shutdown_background), which says it shuts down the runtime without waiting, but here it is clearly waiting for something

The expectation, of course, is that the program terminates even if the `block_on` future panics and there is an uncooperative task outstanding.

**Comment by Darksonn** [comment] 2022-06-22 06:18
As far as I can tell, the call to `block_on` _does_ panic. The program doesn't terminate because the panic stops the program from reaching the `shutdown_background` call, so the `Runtime` destructor runs instead, which will wait for tasks to get terminated.

(The destructor aborts all tasks, but aborting a running task doesn't take effect until the task reaches an `.await` where it can be killed.)

**Comment by Darksonn** [comment] 2022-08-10 14:30
Closing as not a bug.

**Closed by Darksonn** 2022-08-10 14:30 UTC
Labels: C-bug, A-tokio, M-task
