### ISSUE TITLE
tokio-tcp: no obvious way to convert tokio::net::TcpStream to std::net::TcpStream

### ISSUE THREAD

**Issue by kpcyrd** [tokio-rs/tokio#856] opened 2019-01-16 23:21 UTC
## Version

tokio-tcp: 0.1.3

## Description

tokio-fs has a function [`into_std`](https://docs.rs/tokio/0.1.14/tokio/fs/struct.File.html#method.into_std), I'm trying to do the same with tokio-tcp but there doesn't seem to be such a function.

I'm trying to go from `tokio::net::TcpStream` to `std::net::TcpStream`.

This code works but I'm not sure this is the best approach:
```rust
let mut rt = Runtime::new()?;
let socket = rt.block_on(fut)?; // create the socket

use std::os::unix::io::AsRawFd;
use std::os::unix::io::FromRawFd;
let socket2 = unsafe { TcpStream::from_raw_fd(socket.as_raw_fd()) };
let socket = socket2.try_clone()?;
```

**Comment by kpcyrd** [comment] 2019-01-17 17:20
I've noticed my workaround doesn't work on non-unix because AsRawHandle isn't implemented for windows.

**Comment by carllerche** [comment] 2019-02-20 18:34
This is by design due to https://github.com/carllerche/mio/pull/859.

Mio 0.7 will hopefully address this. I will close the issue for now as there are no immediate steps to take.

**Closed by carllerche** 2019-02-20 18:34 UTC
Labels: tokio-io
