### ISSUE TITLE
[tokio-async-await] Stream support

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/tokio#595] opened 2018-08-29 13:24 UTC
I was trying to port over some server code using `hyper` and I ran into this error:

```
error[E0277]: `(dyn futures::stream::Stream<Item=hyper::Chunk, Error=std::boxed::Box<(dyn std::error::Error + std::marker::Sync + std::marker::Send + 'static)>> + std::marker::Send + 'static)` cannot be shared between threads safely
```

After asking on Gitter, the issue might be that the compiler doesn't recognize that `hyper::Body` (which is, more or less, a `Stream`) can be `Unpin`.

**Comment by carllerche** [comment] 2018-09-01 00:02
The problem is that `Unpin` is not implemented for trait objects.

The fix for this will take a few changes:

* https://github.com/rust-lang/rust/pull/53874
* https://github.com/rust-lang-nursery/futures-rs/pull/1239

**Comment by vorot93** [comment] 2018-12-05 15:41
@carllerche Both seem to have been closed some time ago.

**Comment by carllerche** [comment] 2019-01-03 05:40
I think this may no longer be an issue. I'm going to close it. If I am wrong, please reply as I misunderstood the problem.

**Closed by carllerche** 2019-01-03 05:40 UTC
Labels: tokio-async-await
