### ISSUE TITLE
tokio::process::Command::spawn can fail with WouldBlock

### ISSUE THREAD

**Issue by Yoric** [tokio-rs/tokio#2841] opened 2020-09-17 13:44 UTC
**Version**

- tokio v0.2.22
- tokio-macros v0.2.5
- tokio-test v0.2.1
- rustc 1.48.0-nightly (9b4154193 2020-09-14)

**Platform**

```
Darwin * 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

**Description**

While stress-testing a process library I'm writing, I encountered somewhat reproducible instances of

```rust
let child = tokio::process::Command::new("...")
   .stdout(std::process::Stdio::piped())
   .spawn()
   .unwrap();
```

failing with a `WouldBlock` error.

I expected that the underlying error would simply cause a future to be blocked, rather than returning a `Result::Err`.

**Comment by Yoric** [comment] 2020-09-17 13:58
By the way, if this is confirmed to be an unwanted behavior, I'm interested in working on a patch.

**Comment by ipetkov** [comment] 2020-09-17 17:27
Hi @Yoric thanks for the report!

Can't think of what would raise a `WouldBlock` error here, other than a potential issue with registering a signal handler under the hood (which internally uses a pipe for receiving wake events).

Could you try to reproduce this while running under `strace` and post the log here?

**Comment by Yoric** [comment] 2020-09-17 17:39
I'll try and do that.
The test lasted 50 minutes, though, so... I'm a bit afraid of the size of the log.

**Comment by ipetkov** [comment] 2020-09-17 17:59
@Yoric if you're interested in checking out the tokio source and annotating the code with extra debug statements or context of where the error comes out from that might also help narrow down the cause

**Comment by Yoric** [comment] 2020-09-18 07:20
Minimal test:

```rust
// Attempt to stress tokio::process::Command::spawn
// to reproduce a `WouldBlock` error.
#[test]
fn main() {
    env_logger::init();
    tokio_test::block_on(async {
        let mut cmd = tokio::process::Command::new("ls");
        cmd.kill_on_drop(true) // Cleanup at the end of the test
            .stdout(std::process::Stdio::piped());
        let mut  processes = vec![];
        for i in 0..10000 {
            eprintln!("Process {}", i);
            processes.push(cmd.spawn().unwrap());
        }
    });
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', tests/stress_command.rs:13:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b4154193e8471f36b1a9e781f1ef7d492fc6a6c/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/9b4154193e8471f36b1a9e781f1ef7d492fc6a6c/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/9b4154193e8471f36b1a9e781f1ef7d492fc6a6c/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /Users/dteller/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973
   4: stress_command::main::{{closure}}
             at ./tests/stress_command.rs:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/dteller/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
   6: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
   7: tokio::coop::with_budget::{{closure}}
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
   8: std::thread::local::LocalKey<T>::try_with
             at /Users/dteller/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:271
   9: std::thread::local::LocalKey<T>::with
             at /Users/dteller/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:247
  10: tokio::coop::with_budget
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  11: tokio::coop::budget
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  12: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  13: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  15: tokio::runtime::basic_scheduler::enter
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  16: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  17: tokio::runtime::Runtime::block_on::{{closure}}
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  18: tokio::runtime::context::enter
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  19: tokio::runtime::handle::Handle::enter
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  20: tokio::runtime::Runtime::block_on
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  21: tokio_test::block_on
             at /Users/dteller/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-test-0.2.1/src/lib.rs:37
  22: stress_command::main
             at ./tests/stress_command.rs:6
  23: stress_command::main::{{closure}}
             at ./tests/stress_command.rs:4
  24: core::ops::function::FnOnce::call_once
             at /Users/dteller/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  25: core::ops::function::FnOnce::call_once
             at /rustc/9b4154193e8471f36b1a9e781f1ef7d492fc6a6c/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Yoric** [comment] 2020-09-18 11:14
I fear that any solution would require a rewrite of `spawn()` with a different signature – the current definition is sync, so cannot be `await`-ed upon and any launch error can happen after the `Child` has been returned.

By the way, shouldn't `kill()`  be `async` and/or return a `Future`?

**Comment by Yoric** [comment] 2020-09-18 11:50
> @Yoric if you're interested in checking out the tokio source and annotating the code with extra debug statements or context of where the error comes out from that might also help narrow down the cause

Actually, I think the reason is simple: the Unix implementation of `spawn_child` [immediately calls](https://github.com/tokio-rs/tokio/blob/842d5565bdd4310cd96386a8ffa9949b24c5856f/tokio/src/process/unix/mod.rs#L99) `cmd.spawn()?`. This can error with a `WouldBlock` if `posix_spawn` or `exec` errors with `EAGAIN`.

I'm not entirely sure how we can wait for `posix_spawn` or `exec` to be available once more without polling.

**Comment by ipetkov** [comment] 2020-09-18 17:01
Thanks for pulling some logs @Yoric, I'll take a look at them.

Actually I also came across [this comment](https://github.com/ninja-build/ninja/pull/1650#discussion_r326793174) which points towards `EAGAIN` being raised when the process limit is exhausted which I suspect may be the case in your stress test. I also noticed that the test calls `kill` but does not await the child, which leaves the possibility of the process not getting reaped (tokio will perform a best effort for reaping orphaned children in the background, so long as new process are being spawned/polled, but I suppose it is possible for that to get stuck).

The master branch has a change which makes `kill()` and async operation which also internally reaps the child to minimize the possibility of leaving a zombie process. **Could you try rerunning your test with the latest master commit and see if the issue persists (or at least takes even longer to hit)?**

**Comment by Yoric** [comment] 2020-09-18 17:16
> I also noticed that the test calls `kill` but does not await the child, which leaves the possibility of the process not getting reaped (tokio will perform a best effort for reaping orphaned children in the background, so long as new process are being spawned/polled, but I suppose it is possible for that to get stuck).

Yes, that's also my assumption. I have added a `wait_with_output` call and that solves the issue.

So, the question is which behavior is desirable:

- somehow making `spawn` (or a variant thereof) wait until a process can be spawned; or
- keeping it a failure as it is at the moment, perhaps with more documentation.

**Comment by ipetkov** [comment] 2020-09-18 17:19
We should definitely update the documentation to mention that a `WouldBlock` error can be raised during `spawn` if the pid space is full!

As for waiting until the spawn succeeds I'm not sure what we can do to be woken up when the process space clears out. It is entirely possible that the system has too many other processes running even beyond tokio's control. Happy to explore any suggestions if anyone has them! But until then I think the best course of action is to surface the error to the caller and allow them to retry if necessary...

**Comment by ipetkov** [comment] 2020-10-13 00:42
The documentation around returning `WouldBlock` has been updated as part of #2952. Unfortunately there doesn't seem like we can do anything about the system pid exhaustion, or how to be alerted/woken if more space opens up. Going to close this out for now, feel free to reopen if there are other questions!

**Closed by ipetkov** 2020-10-13 00:42 UTC
Labels: A-tokio, C-bug, M-process
