### ISSUE TITLE
Can not build runtime with runtime::Builder::new()

### ISSUE THREAD

**Issue by goriunov** [tokio-rs/tokio#2316] opened 2020-03-13 08:32 UTC
## Version

Latest 0.2.x

## Platform
Arch linux 64-bit

## Description

Trying to build run time with Builder:

```
 let mut rt = runtime::Builder::new().build().unwrap();

 rt.block_on(async {})
```
Throws:

```
 thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', src/libcore/option.rs:1188:5
```

Below works properly:
```
 let mut rt = runtime::Runtime::new()?;

 rt.block_on(async {})
```

**Comment by hawkw** [comment] 2020-03-13 21:06
By default, the `runtime::Builder` will create an empty "shell" runtime that doesn't actually do anything. In order to actually run futures, you will need to call [`Builder::threaded_scheduler`](https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.threaded_scheduler) or [`Builder::basic_scheduler`](https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.basic_scheduler) to configure how the runtime will schedule futures, and probably [`Builder::enable_io`](https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.enable_io) and/or [`Builder::enable_time`](https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.enable_time) to enable the IO reactor and timer, respectively (you can also use [`Builder::enable_all`](https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Builder.html#method.enable_all) to get both). 

Constructing the same runtime returned by `runtime::Runtime::new()` using the builder would look something like this (assuming `features = ["full"]`):
```rust
let mut rt = runtime::Builder::new()
   .threaded_scheduler()
   .enable_all()
   .build()
   .unwrap();
// ...
```

You can also see [here](https://docs.rs/tokio/0.2.13/tokio/runtime/index.html#runtime-configurations) for details.

**Comment by goriunov** [comment] 2020-03-15 05:08
Oh, i see thanks for clarification :)

**Comment by hawkw** [comment] 2020-03-15 18:39
No problem, glad I could help!

Mind if I close this issue, or do you think there are any docs changes we could make to clear this up?

**Comment by goriunov** [comment] 2020-03-15 18:55
@hawkw IMHO this is good candidate for examples, as at the start i went through examples and could not find how to set it up. Then i jumped in to https://docs.rs/tokio/0.2.13/tokio/runtime/index.html#basic-scheduler docs, looking now i can see this note https://docs.rs/tokio/0.2.13/tokio/runtime/index.html#resource-drivers (at the bottom), may be better to move this note before actual config... or mention directly in each description (Threaded Scheduler and Basic Scheduler)...

**Comment by balboah** [comment] 2020-03-17 07:33
It would be awesome if there were more hints from the error `thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime'` that you need to do the `.enable_all()` to get it running.
Easy to miss this part and it doesn't ring a bell when you're new to Tokio :)

**Comment by tatsuya6502** [comment] 2020-04-11 05:12
I ran into this error and had no clue that I needed to do `enable_all()`. Perhaps adding the following hint to the `there is no reactor running` message might help:

`Hint: If you have built the runtime with a Builder, try calling enable_all() to enable I/O and time drivers`

**Comment by Darksonn** [comment] 2020-04-29 21:16
Closing as duplicate of #2465.

**Closed by Darksonn** 2020-04-29 21:16 UTC
Labels: A-tokio, C-question, M-runtime, T-docs
