### ISSUE TITLE
calling `tokio::spawn` panic in dynamic library

### ISSUE THREAD

**Issue by cppcoffee** [tokio-rs/tokio#5966] opened 2023-08-31 10:21 UTC
**Version**
tokio v1.32.0

**Platform**
64-bit osx and 64-bit linux

**Description**

Using `libloading` to load dynamic library, and then calling the `extern "C" start_worker()` function, tokio is not working.

panic message:
```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', my-plugin/src/lib.rs:13:5
```

I tried this code:
This is the test code that can be reproduced
[plugin-example.zip](https://github.com/tokio-rs/tokio/files/12485054/plugin-example.zip)

I expected to see this happen: tokio can spawn

Instead, this happened: no found tokio context

**Comment by taiki-e** [comment] 2023-08-31 10:25
Duplicate of #5311, https://github.com/tokio-rs/tokio/discussions/5299, etc.

**Closed by taiki-e** 2023-08-31 10:25 UTC
Labels: C-bug, A-tokio

**Comment by mluettecke** [comment] 2024-07-21 13:03
@cppcoffee Did you ever solve or found a workaround for this?

**Comment by cppcoffee** [comment] 2024-07-22 01:06
> @cppcoffee Did you ever solve or found a workaround for this?

No solution found.
