### ISSUE TITLE
Channel Wait type is gone

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/tokio#1959] opened 2019-12-14 12:19 UTC
The channel senders used to have a wait() method that retuned a sync interface to them. This is gone in 0.2. Is there a replacement available?

For context: I was using it to expose a Write implementation for an async stream. Is there a better way to do this? Should try to grab a reference to the Runtime and use block_on?

**Comment by sfackler** [comment] 2019-12-14 12:32
futures::executor::block_on(chan.next())

**Comment by lnicola** [comment] 2019-12-14 13:11
Teah, I imagine that would work. Thanks

**Comment by carllerche** [comment] 2019-12-14 19:16
I would like to bring back *something*... maybe `.blocking()` instead, specifically for channels as it is a common case.

**Comment by Darksonn** [comment] 2020-07-25 09:58
Closing as duplicate of #2629.

**Closed by Darksonn** 2020-07-25 09:58 UTC
