### ISSUE TITLE
`tokio::io::duplex` with small `max_buf_size` block infinite

### ISSUE THREAD

**Issue by comphilip** [tokio-rs/tokio#5313] opened 2022-12-27 01:43 UTC
**Version**
`tokio`: 1.23.0

**Platform**
Rust Playground

**Description**
[Rust doc](https://docs.rs/tokio/latest/tokio/io/fn.duplex.html) has too little information about `max_buf_size`, it sounds like the `max_buf_size` is a performance hint: If setting a improper value, performance will be lower but it should still works.

Well, setting `max_buf_size` to 0 will be blocked infinite. More worse, if `max_buf_size` is smaller for a single data chunk, it also blocked.

I tried this code:

```rust
use tokio; // 1.23.0
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use std::io::Result;

#[tokio::main(flavor="current_thread")]
async fn main() -> Result<()> {
    const MAX_BUF_SIZE: usize = 2; // lower than single ping or pong
    let (mut client, mut server) = tokio::io::duplex(MAX_BUF_SIZE);

    client.write_all(b"ping").await?;
    
    let mut buf = [0u8; 4];
    server.read_exact(&mut buf).await?;
    assert_eq!(&buf, b"ping");
    
    server.write_all(b"pong").await?;
    
    client.read_exact(&mut buf).await?;
    assert_eq!(&buf, b"pong");
    Ok(())
}
```
I expected to see this happen: 

no matter what `max_buf_size` is 0 ~ 3, it works well.

Instead, this happened: 

the code runs timeout and killed if `max_buf_size` smaller than 4.

**Comment by Darksonn** [comment] 2022-12-27 09:25
This is expected behavior. The `write_all` call waits until all four bytes are written, but only two bytes can fit in the buffer. Additionally, the server does not start reading until _after_ all four bytes are written. Because of this, it blocks forever.

To see a program where the buffer size doesn't matter, separate server and client into separate tasks so that they do not block each other:
```Rust
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use std::io::Result;

#[tokio::main(flavor="current_thread")]
async fn main() -> Result<()> {
    const MAX_BUF_SIZE: usize = 2; // lower than single ping or pong
    let (mut client, mut server) = tokio::io::duplex(MAX_BUF_SIZE);
    
    let server_jh = tokio::spawn(async move {    
        let mut buf = [0u8; 4];
        server.read_exact(&mut buf).await?;
        assert_eq!(&buf, b"ping");
        
        server.write_all(b"pong").await?;
        Ok(())
    });

    client.write_all(b"ping").await?;

    let mut buf = [0u8; 4];
    client.read_exact(&mut buf).await?;
    assert_eq!(&buf, b"pong");
    
    server_jh.await.unwrap()
}
```
Closing as intended behavior.

**Closed by Darksonn** 2022-12-27 09:25 UTC
Labels: C-bug, A-tokio, M-io
