### ISSUE TITLE
WatchStream ignore the first receiver's update

### ISSUE THREAD

**Issue by Liyixin95** [tokio-rs/tokio#4006] opened 2021-07-30 04:50 UTC
**Version**
tokio v1.9.0
tokio-stream v0.1.7

**Platform**
Windows10 64-bit 

**Description**
The WatchStream created from a already updated receiver(call `borrow_and_update`) will still produce the outdated item.

I tried this code:

```
  let (tx, mut rx) = watch::channel("first".to_string());
  rx.borrow_and_update();

  let mut st = WatchStream::new(rx);
  assert_eq!(st.next().await.unwrap(), "first");
```

I expected to see this happen: the watch stream should be blocked.

Instead, this happened: the watch stream produce string "first".

I'm not sure if it was intended behavior. But if this is a real problem, then I would like to provide a PR.

**Comment by Darksonn** [comment] 2021-07-30 07:28
The problem is that the first item is already considered seen even if you don't do the `borrow_and_update` call, so the only way to get it to stop doing this would lead to it never yielding the first item.

**Comment by Darksonn** [comment] 2021-09-19 15:26
I'll be closing this issue. It's not something we can change without breaking changes.

**Closed by Darksonn** 2021-09-19 15:26 UTC
Labels: C-bug, M-sync, A-tokio-stream
