### ISSUE TITLE
A `const` item should never be interior mutable

### ISSUE THREAD

**Issue by fgaud** [tokio-rs/tokio#4872] opened 2022-07-27 22:22 UTC
**Version**
```
 cargo tree | grep tokio
│   │   │   │   └── tokio v1.20.1
│   │   │   │       └── tokio-macros v1.8.0 (proc-macro)
│   │   │   │   └── tokio v1.20.1 (*)
│   │   │   └── tokio v1.20.1 (*)
│   └── tokio v1.20.1 (*)
│   │   │   └── tokio v1.20.1 (*)
│   │   │   ├── tokio v1.20.1 (*)
│   │   │   └── tokio-stream v0.1.9
│   │   │       └── tokio v1.20.1 (*)
│   │   ├── tokio v1.20.1 (*)
│   │   ├── tokio-stream v0.1.9 (*)
│   │   │   └── tokio v1.20.1 (*)
│   │   └── tokio v1.20.1 (*)
│   ├── tokio v1.20.1 (*)
│   ├── tokio-stream v0.1.9 (*)
│   └── tokio v1.20.1 (*)
├── tokio v1.20.1 (*)
└── tokio-stream v0.1.9 (*)
    ├── tokio v1.20.1 (*)
    ├── tokio-stream v0.1.9 (*)
```

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

`Linux ... #1 SMP Wed May 25 23:50:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

With Tokio 1.20, the following code would generate a Clippy error
```
use std::sync::Mutex;
use std::sync::Arc;

tokio::task_local!(static DATA: Arc<Mutex<u32>>);

#[tokio::main]
async fn main() {
    let _ = get_data().unwrap();
}

pub fn get_data() -> Option<Arc<Mutex<u32>>> {
    DATA.try_with(|rt| rt.clone()).ok()
}
```

```
warning: a `const` item should never be interior mutable
 --> amzn_s3_bloblib_cli/src/simple_test.rs:4:1
  |
4 | tokio::task_local!(static DATA: Arc<Mutex<u32>>);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This prevented us from updating tokio since we has a no-warning policy. We can ignore that warning but it feels wrong that a tokio change in a macro generates warning in the caller's code.

I think this is a consequence of this commit introducing the `const` keyword in the macro
https://github.com/tokio-rs/tokio/commit/7f92bce39f7046e204381127936e2014094f9638#diff-44deb4799d4149efed5ce1d16e8f355ad2ce1d133613475fc813cd58af8798b4R57

**Comment by hawkw** [comment] 2022-07-27 22:39
This lint sometimes generates false positives; it also sometimes is triggered when a constant is used as an array initializer to initialize an array with an interior-mutable item...

We should probably add an `#[allow(...)]` attribute for this lint in the macro, but it might be worth considering changing the lint upstream...

**Comment by Darksonn** [comment] 2022-07-28 07:10
This is clippy bug https://github.com/rust-lang/rust-clippy/issues/9224. Supposedly a fix was merged three days ago.

**Comment by fgaud** [comment] 2022-07-28 16:45
Cool, thanks for link! Sorry for the duplicate, search searches by default on open issues only :(

**Comment by Darksonn** [comment] 2022-09-22 22:02
The issue is closed on the clippy side, so I am also closing this here.

**Closed by Darksonn** 2022-09-22 22:02 UTC
Labels: C-bug, A-tokio, M-task
