### ISSUE TITLE
100% cpu usage on Mac

### ISSUE THREAD

**Issue by ntkoopman** [tokio-rs/tokio#543] opened 2018-08-14 01:25 UTC
I've made a small transparant proxy, but after a while it starts using 100% cpu.

This is my current code, but the behaviour is the same with the code in the [proxy example](https://github.com/tokio-rs/tokio/blob/master/examples/proxy.rs), which uses a Mutex to access the TcpStream:

```rust
let client_writer = client.try_clone().unwrap();
let proxy_writer = proxy.try_clone().unwrap();

let client_to_server = tokio::io::copy(client, proxy_writer)
    .and_then(move |(_, _, writer)| writer.shutdown(Shutdown::Write));

let server_to_client = tokio::io::copy(proxy, client_writer)
    .and_then(move |(_, _, writer)| writer.shutdown(Shutdown::Write));
```

Inspecting the process with dtruss shows that it keeps polling:

```
recvfrom(0x2B, 0x10F687000, 0x800)               = -1 Err#35
recvfrom(0x6D, 0x10F6D9800, 0x800)               = -1 Err#35
recvfrom(0x84, 0x10F6D8000, 0x800)               = -1 Err#35
recvfrom(0x24, 0x10F684000, 0x800)               = -1 Err#35
recvfrom(0x1E, 0x10F6A8000, 0x800)               = -1 Err#35
recvfrom(0x80, 0x10F6A9800, 0x800)               = -1 Err#35
recvfrom(0x6F, 0x10F68D000, 0x800)               = -1 Err#35
recvfrom(0x28, 0x10F687800, 0x800)               = -1 Err#35
recvfrom(0x7C, 0x10F690800, 0x800)               = -1 Err#35
...
```
(Err#35 is EAGAIN)

In all of these cases, on of the two `tokio::io::copy` has finished and then the other direction enters the loop. In most cases the other side also closes the connection and everything works correctly.

If I change the shutdown to use `Shutdown::Both` instead the problem goes away, but then some applications being proxied stop working correctly.

**Comment by carllerche** [comment] 2018-08-14 02:56
Do you have a full example that can be run?

**Comment by SerhoLiu** [comment] 2018-08-15 00:56
@ntkoopman looks like this? https://github.com/tokio-rs/tokio/issues/449

**Comment by hawkw** [comment] 2018-08-21 21:02
Hi @ntkoopman, can I get you to try the current master version of `tokio` and see if this issue persists? It's possible this is related to issue #449, as @SerhoLiu pointed out, and that issue appears to be fixed on master. Knowing if this persists on the latest master or not would help shine some insight into the cause of this problem.

**Comment by hawkw** [comment] 2018-08-23 20:16
Hi @ntkoopman, I haven't been able to reproduce the 100% CPU usage after modifying the `proxy` example on master to use the code you posted above. I'm on macOS 10.12.6 and testing against the current `tokio` master (8bf2e9aeb063b8eca8a207cdbf9eb5e6046f8aeb_. 

Would you be willing to provide a full runnable example that causes the CPU usage spike?

**Comment by ntkoopman** [comment] 2018-08-24 14:03
I updated to the latest master and also haven't seen the issue again, although I haven't tested very extensively. I'll assume it's fixed and reopen if it reappears.
Thank you for your help!

**Closed** 2018-08-24 14:03 UTC
