### ISSUE TITLE
Support cfg branches in `tokio::select!`

### ISSUE THREAD

**Issue by mcches** [tokio-rs/tokio#5860] opened 2023-07-11 22:16 UTC
**Is your feature request related to a problem? Please describe.**

Unable to have conditionally compiled branches in a `tokio::select!`.

```rust
#[cfg(test)]
mod test {
    #[tokio::test]
    async fn select_with_cfg() {
        tokio::select! {
            #[cfg(feature = "sim")]
            _ = futures::future::pendind() => {}
        }
    }
}
```

```txt
no rules expected the token `#`
no rules expected this token in macro call rustc(Click for full compiler diagnostic)
select.rs(415, 6): while trying to match `@`
```

**Describe the solution you'd like**
I'd like to be able to conditionally compile branches in a `tokio::select!`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by taiki-e** [comment] 2023-07-12 04:08
Duplicate of #3974.

**Closed by taiki-e** 2023-07-12 04:08 UTC
Labels: A-tokio, C-feature-request, M-macros
