### ISSUE TITLE
Absurd compile times for simple project (9m+)

### ISSUE THREAD

**Issue by mteam88** [tokio-rs/tokio#5242] opened 2022-11-29 14:47 UTC
**Version**
```
│   │   │   │   │   ├── tokio v1.22.0
│   │   │   │   │   │   └── tokio-macros v1.8.0 (proc-macro)
│   │   │   │   │   ├── tokio-util v0.7.4
│   │   │   │   │   │   ├── tokio v1.22.0 (*)
│   │   │   │   │   ├── tokio v1.22.0 (*)
│   │   │   │   │   ├── tokio v1.22.0 (*)
│   │   │   │   │   └── tokio-rustls v0.23.4
│   │   │   │   │       ├── tokio v1.22.0 (*)
│   │   │   │   ├── tokio v1.22.0 (*)
│   │   │   │   ├── tokio-rustls v0.23.4 (*)
│   │   │   │   │   ├── tokio v1.22.0
│   │   │   │   │   ├── tokio-rustls v0.23.4 (*)
│   │   │   ├── tokio v1.22.0 (*)
│   │   │   ├── tokio-tungstenite v0.17.2
│   │   │   │   ├── tokio v1.22.0 (*)
│   │   │   │   ├── tokio-rustls v0.23.4 (*)
│   │   ├── tokio v1.22.0 (*)
│       │   ├── tokio v1.22.0 (*)
│       ├── tokio v1.22.0 (*)
└── tokio v1.22.0 (*)
```

**Platform**
`Linux codespaces-15f5ec 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Github codespace 2 cores
(similar absurd compile times on my 4 core pc)
**Description**
I have absurdly high compile times on all default settings for a very basic tokio project. I don't know if this is normal for tokio, but if so, It makes tokio unusable. Waiting 9m to compile 30 lines of code is unacceptable.
The first build sees a compilation of all dependencies (and takes 10m-12m), but further builds only build `project-name(bin)` according to `cargo build` output.

The code is here:
https://github.com/gakonst/ethers-rs/blob/master/examples/subscribe_logs.rs

**Comment by Darksonn** [comment] 2022-11-29 16:20
Compiling Tokio certainly doesn't take anywhere near 9 minutes. For example, to build a simple example from scratch with no incremental compilation, I get the following:
```
$ rm -rf target && cargo build
   Compiling libc v0.2.137
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling cfg-if v1.0.0
   Compiling parking_lot_core v0.9.5
   Compiling syn v1.0.104
   Compiling log v0.4.17
   Compiling scopeguard v1.1.0
   Compiling memchr v2.5.0
   Compiling smallvec v1.10.0
   Compiling bytes v1.3.0
   Compiling pin-project-lite v0.2.9
   Compiling lock_api v0.4.9
   Compiling tokio v1.22.0
   Compiling signal-hook-registry v1.4.0
   Compiling num_cpus v1.14.0
   Compiling mio v0.8.5
   Compiling socket2 v0.4.7
   Compiling parking_lot v0.12.1
   Compiling tokio-macros v1.8.1
   Compiling tokioct v0.1.0 (/tmp/tokioct)
    Finished dev [unoptimized + debuginfo] target(s) in 12.29s
```

```toml
[dependencies]
tokio = { version = "1", features = ["full"] }
```
```rs
#[tokio::main]
async fn main() {
    println!("Hello, world!");
}
```
Although 12 seconds isn't particularly impressive, it is quite far from being as bad as what you are observing. I wasn't able to build your example, but I would guess that the problem is the final linking step of creating the final executable. This step scales with the number of dependencies you have, and you have _a lot_ of dependencies. One thing you could try is to use the `mold` linker, which is generally known to be faster.

Since the problem is unrelated to Tokio, I will close this issue. That said, feel free to post additional questions here.

**Closed by Darksonn** 2022-11-29 16:20 UTC
Labels: C-bug, A-tokio

**Comment by mteam88** [comment] 2022-12-09 13:48
Thanks for your help. Though the problem only occurred when using tokio, I believe it was _not_ the linker: I had been using mold for some time. It turns out the problem was simple: I was building this code in WSL, which is notoriously bad at IO heavy operations like compiling.

As far as tokio goes, it may compile slower with tokio only because tokio has so many dependencies, I am not skilled enough to debug this further...

Thank you!

**Comment by Darksonn** [comment] 2022-12-11 09:54
The build happening in WSL is indeed a plausible source of the problem.

> because tokio has so many dependencies

When I run `cargo build` in the repository you gave me, the build involves 430 dependencies, whereas the simple Tokio build I posted above has 22. It's a drop in the ocean compared to your project.

**Comment by mteam88** [comment] 2022-12-11 22:04
> When I run `cargo build` in the repository you gave me, the build involves 430 dependencies, whereas the simple Tokio build I posted above has 22. It's a drop in the ocean compared to your project.

Ah good point, I was looking at the wrong thing. My bad. 
Keep on doing what your doing. Great stuff.
Thanls!
