### ISSUE TITLE
Sleep is not firing when macOS goes to sleep and then awakens

### ISSUE THREAD

**Issue by phillipCouto** [tokio-rs/tokio#5894] opened 2023-07-28 17:39 UTC
**Version**
```
│   │   │   │   │   │   │   ├── tokio v1.29.1
│   │   │   │   │   │   │   │   ├── tokio-macros v2.1.0 (proc-macro)
│   │   │   │   │   │   │   ├── tokio-util v0.7.8
│   │   │   │   │   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   │   │   ├── tokio-util v0.7.8 (*)
│   │   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   │   └── tokio-io-timeout v1.2.0
│   │   │   │   │       └── tokio v1.29.1 (*)
│   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   ├── tokio-stream v0.1.14
│   │   │   │   │   ├── tokio v1.29.1 (*)
│   │   │   │   │   └── tokio-util v0.7.8 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   ├── tokio-stream v0.1.14 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   └── tokio-native-tls v0.3.1
│   │       └── tokio v1.29.1 (*)
│   │   ├── tokio v1.29.1 (*)
│   │   │   ├── tokio v1.29.1 (*)
│   │   │   ├── tokio-native-tls v0.3.1 (*)
│   │   └── tokio v1.29.1 (*)
│   ├── tokio v1.29.1 (*)
│   ├── tokio-stream v0.1.14 (*)
├── tokio v1.29.1 (*)
└── tokio v1.29.1 (*)
```

**Platform**
`Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64`

**Description**
Enter your issue details here.
One way to structure the description:

It seems like `tokio::time::sleep`  resources are not firing when the device goes to sleep and is reawaken. In our code we are using `timeout` to cancel an HTTP request when the duration is reached but in the screenshot you can see the sleeps are far exceeding their set duration.

The application is a program that runs as a service to keep files locally on the users machine in sync with the platform. Users frequently put their devices to sleep usually at the end of the day resulting in long running sessions of the service and these timers accumulating. We have observed the service will get to a point were it can no longer make anymore HTTP requests and the sync process is stuck requiring the user to restart the application.

I am not sure if this is a bug or just a lack of understanding with tokio and how requests should be cancelled.

Here is the code we use to wrap a request with a timeout:

```rust
async fn with_timeout(
    size: Option<usize>,
    resp: ResponseFuture,
) -> Result<Response<Body>, ApiErrors> {
    let timeout_dur = match size {
        Some(size) => Duration::from_secs(calculated_timeout(size)),
        None => Duration::from_secs(30),
    };

    let result = match timeout(timeout_dur, resp).await {
        Err(e) => return Err(ApiErrors::Elapsed(e)),
        Ok(r) => r,
    };

    result.map_err(ApiErrors::Error)
}
```

`calculated_timeout` is just a function to calculate a timeout for a request with a size (uploading or downloading files) so the timeout is equivalent to the request completing with a transfer rate of 20 KBps.

Unfortunately I have not created a simple example demonstrating the issue. I will try to do that but wanted to post the issue first in case it is an issue with how we are setting the timeout or if there are known gotchas with timeouts and a device going to sleep for extended periods of time (> 1 hour).

![Screenshot 2023-07-28 at 13 08 15](https://github.com/tokio-rs/tokio/assets/382715/fb2ea687-8e9b-4295-a45a-a124576a5f52)

**Comment by Darksonn** [comment] 2023-07-28 20:14
Time spent during suspend is not counted towards timers on some operating systems.

**Comment by phillipCouto** [comment] 2023-07-28 20:45
> Time spent during suspend is not counted towards timers on some operating systems.

The confusing part for me is how is the tokio-tracing able to see the total time for the sleep resource but then the sleep itself is stuck. By the way the screenshot is 10 - 15 minutes after waking the device up after the sleep.

**Comment by Darksonn** [comment] 2023-10-01 20:33
Closing as duplicate of  #3185.

**Closed by Darksonn** 2023-10-01 20:33 UTC
Labels: C-bug, A-tokio, M-time
