### ISSUE TITLE
LinesCodec does not handle newlines in frames

### ISSUE THREAD

**Issue by binomial0** [tokio-rs/tokio#791] opened 2018-12-09 19:53 UTC
## Version

0.1.13, all platforms

## Subcrates

tokio-codec

## Description

If you send a String that contains a newline via a tokio::codec::LinesCodec, the newline is not escaped, and is indistinguishable from a newline at the boundary between two frames. If the result is then decoded by a LinesCodec, the frame will be split in two.

I'd have expected that the input would be faithfully reconstructed, potentially by escaping the newline. If this is not feasible, this behavior should be explicitly documented in the type-level documentation of LinesCodec.

(I think I can PR the implementation / documentation - but I can't decide if this should be fixed, or if it works as intended and should simply be documented.)

**Comment by tobz** [comment] 2018-12-10 17:01
This is intended behavior, and could stand to be documented, yeah.

I don't think there's a reasonable default we could assume for what the
right way to escape it would be, and should instead leave it to the user.

**Comment by tobz** [comment] 2018-12-17 19:59
Gonna close this.  We would definitely appreciate a PR if you were willing. :)

**Closed by tobz** 2018-12-17 19:59 UTC

**Comment by carllerche** [comment] 2019-01-03 05:53
For more context, this behavior was copied from std.
