### ISSUE TITLE
Prevent ignoring `spawn_blocking` future

### ISSUE THREAD

**Issue by CertainLach** [tokio-rs/tokio#2762] opened 2020-08-11 17:13 UTC
**Is your feature request related to a problem? Please describe.**
Stuck for 1 hour while debugging "deadlocking code", then found panic, which i had ignored in `spawn_blocking` call, which is not marked as `must_use`

**Describe the solution you'd like**
Make spawn_blocking `#[must_use]`

**Describe alternatives you've considered**

**Additional context**

**Comment by Darksonn** [comment] 2020-08-11 17:20
This seems like a near-duplicate of #1830.

**Comment by CertainLach** [comment] 2020-08-11 17:31
Somehow missed this issue while searching for duplicates.

However, my proposal has a different motivation, instead of implementing different `JoinHandle` `Drop` behavior, i propose to make just harder to miss a panic in spawned blocking code

**Comment by Darksonn** [comment] 2020-08-11 18:12
The `JoinHandle` type is also used by `tokio::spawn`, whose return value is commonly ignored.

**Comment by carllerche** [comment] 2020-10-25 17:43
This is not a change for spawn blocking.

**Closed by carllerche** 2020-10-25 17:43 UTC
Labels: A-tokio, C-feature-request
