### ISSUE TITLE
tokio build broken for aarch64-apple-visionos

### ISSUE THREAD

**Issue by coolbluewater** [tokio-rs/tokio#6628] opened 2024-06-10 11:30 UTC
https://github.com/tokio-rs/tokio/issues/6627 was closed because of changes needed in mio.
Those changes have been [merged](https://github.com/tokio-rs/mio/pull/1795), so reopening.

See https://github.com/tokio-rs/tokio/issues/6627 for details.

**Comment by Darksonn** [comment] 2024-06-10 12:49
Closing as duplicate of #6627.

**Closed by Darksonn** 2024-06-10 12:49 UTC
Labels: C-bug, A-tokio
