### ISSUE TITLE
Panic during shutdown_now blocks indefinitely

### ISSUE THREAD

**Issue by PvdBerg1998** [tokio-rs/tokio#1584] opened 2019-09-21 19:19 UTC
## Version
`"=0.2.0-alpha.5"`

## Platform

Windows 10, msvc

## Subcrates

`tokio-executor`

## Description

During shutdown of my program, I call `runtime::shutdown_now`. However, somewhere in my code a panic is caused when this happens (inside a `Drop`), and this causes the `shutdown_now` to never return.

**Comment by carllerche** [comment] 2019-10-02 17:53
Are you able to provide a test case or reproduction code?

**Comment by PvdBerg1998** [comment] 2019-10-02 17:57
@carllerche Not atm, but it shouldn't be too hard to create a structure that panics on drop and launch that into the runtime via eg. poll_fn or similar.

**Comment by kaimast** [comment] 2019-10-10 01:41
Are there cases where shutdown_now will not work? My codebase gets stuck on it too, but not sure if it is the same issue.

**Comment by hawkw** [comment] 2019-11-15 22:42
Is this still the case on the latest master?

**Comment by carllerche** [comment] 2019-11-22 21:13
I am going to close this as I cannot reproduce and the scheduler / shutdown logic has been completely rewritten.

**Closed by carllerche** 2019-11-22 21:13 UTC
Labels: bug
