### ISSUE TITLE
`Interval::reset_immediately()` is not immediately ready

### ISSUE THREAD

**Issue by erikgrinaker** [tokio-rs/tokio#6940] opened 2024-10-28 12:06 UTC
**Version**

v1.38.1

**Platform**

macOS 15 on `arm64`

```
Darwin 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64 arm Darwin
```

**Description**

`Interval::reset_immediately()` is not immediately ready. It appears to take 1 millisecond (the timer resolution).

```rust
#[tokio::test]
async fn test_reset_immediately() {
    use futures::FutureExt as _;
    use tokio::time::{Duration, Instant};

    let mut ticker = tokio::time::interval(Duration::from_secs(1));
    ticker.tick().await;

    ticker.reset_immediately();
    assert!(ticker.tick().now_or_never().is_some()); // fails

    // Time a reset. Outputs > 1 millisecond.
    let start = Instant::now();
    ticker.reset_immediately();
    ticker.tick().await;
    println!("{}", Instant::now().duration_since(start).as_secs_f64())
}
```

I expect the future to be immediately ready.

**Comment by Darksonn** [comment] 2024-10-28 12:43
This is due to duration-zero sleeps. Duplicate of  #6866.

**Closed by Darksonn** 2024-10-28 12:43 UTC
Labels: C-bug, A-tokio, M-time
