### ISSUE TITLE
tokio runtime regression/behavioral change in 0.1.13

### ISSUE THREAD

**Issue by kahing** [tokio-rs/tokio#810] opened 2018-12-21 20:26 UTC
## Version

tokio 0.1.13

$ cargo tree |grep tokio
│   │   └── tokio-io v0.1.10                                                                                                                                                                          
│   ├── tokio v0.1.13
│   │   ├── tokio-codec v0.1.1
│   │   │   └── tokio-io v0.1.10 (*)
│   │   ├── tokio-current-thread v0.1.4
│   │   │   └── tokio-executor v0.1.5
│   │   ├── tokio-executor v0.1.5 (*)
│   │   ├── tokio-fs v0.1.4
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-threadpool v0.1.9
│   │   │       └── tokio-executor v0.1.5 (*)
│   │   │   └── tokio-io v0.1.10 (*)
│   │   ├── tokio-io v0.1.10 (*)
│   │   ├── tokio-reactor v0.1.7
│   │   │   ├── tokio-executor v0.1.5 (*)
│   │   │   └── tokio-io v0.1.10 (*)
│   │   ├── tokio-tcp v0.1.2
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-reactor v0.1.7 (*)
│   │   ├── tokio-threadpool v0.1.9 (*)
│   │   ├── tokio-timer v0.2.8
│   │   │   └── tokio-executor v0.1.5 (*)
│   │   ├── tokio-udp v0.1.3
│   │   │   ├── tokio-codec v0.1.1 (*)
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-reactor v0.1.7 (*)
│   │   └── tokio-uds v0.2.4
│   │       ├── tokio-codec v0.1.1 (*)
│   │       ├── tokio-io v0.1.10 (*)
│   │       └── tokio-reactor v0.1.7 (*)
│   ├── tokio-executor v0.1.5 (*)
│   ├── tokio-io v0.1.10 (*)
│   ├── tokio-reactor v0.1.7 (*)
│   ├── tokio-tcp v0.1.2 (*)
│   ├── tokio-timer v0.2.8 (*)
└── tokio v0.1.13 (*)

## Platform

Debian 4.9.110-3+deb9u6 x86_64

## Description

I used this construct in my tests which worked fine in tokio 0.1.11 but gets stuck after I upgraded to 0.1.13:
```rust
use futures::future::{self, Future};
use std::io::Write;

fn main() {
    let mut builder = env_logger::Builder::from_default_env();
    builder.format(|buf, record| {
        writeln!(
            buf,
            "{:8} {:24} - {}",
            record.level(),
            std::thread::current().name().unwrap_or("default"),
            record.args()
        )
    });

    let _ = builder.try_init();

    let tfunc = move || -> Result<(), hyper::Error> {
        // test goes here
        let client = hyper::Client::new();
        let res = client
            .get("http://www.example.com".parse().unwrap())
            .wait()?;
        assert_eq!(res.status(), 200);
        Ok(())
    };

    let mut exec = tokio::runtime::Builder::new().build().unwrap();
    exec.block_on(future::lazy(tfunc)).unwrap();
}
```

This is the corresponding working Cargo.toml:
```
[package]
name = "test_client"
version = "0.1.0"
authors = ["Ka-Hing Cheung <kahing@cloudflare.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
futures = "0.1"
hyper = "= 0.12.9"
tokio = "= 0.1.11"
```

If I change to require exactly `tokio = "= 0.1.13"`, the test program does not complete. Turning on trace logging shows:

```
TRACE    main                     - registering with poller
TRACE    main                     - registering with poller
TRACE    main                     - registering with poller
TRACE    main                     - registering with poller
TRACE    main                     - build; num-workers=4
TRACE    main                     - registering with poller
TRACE    main                     - execute; count=1
TRACE    main                     -   -> submitting to random; idx=2
TRACE    tokio-runtime-worker-0   - found work while draining; signal_work
TRACE    tokio-runtime-worker-0   - signal_work -- spawn; idx=3
TRACE    tokio-runtime-worker-0   - Task::run; state=Running
TRACE    tokio-runtime-worker-0   - checkout waiting for idle connection: ("http://www.example.com", Http1)
TRACE    tokio-runtime-worker-1   - Worker::sleep; worker=WorkerId(3)
TRACE    tokio-runtime-worker-1   -   sleeping -- push to stack; idx=3
TRACE    tokio-runtime-worker-1   -     -> starting to sleep; idx=3
TRACE    tokio-runtime-worker-0   - Http::connect; scheme=http, host=www.example.com, port=None
DEBUG    hyper-dns1               - resolving host="www.example.com", port=80
DEBUG    tokio-runtime-worker-0   - connecting to [2606:2800:220:1:248:1893:25c8:1946]:80
TRACE    tokio-runtime-worker-0   - registering with poller
```

It's not exactly the same every time but the program never finishes.

Is this a regression or am I doing something that's no longer supported?

**Comment by stjepang** [comment] 2018-12-24 14:43
> Is this a regression or am I doing something that's no longer supported?

You're doing something that is working in tokio 0.1.11 only by accident. :)

The problem lies in the call to `.wait()`. This method blocks the current thread until the future is resolved. Instead of calling `.wait()`, use combinators like `.and_then()`:

```rust
let tfunc = move || {
    // test goes here
    let client = hyper::Client::new();
    client.get("http://www.example.com".parse().unwrap())
        .and_then(|res| {
            assert_eq!(res.status(), 200);
            Ok(())
        })
};
```

This will work on tokio 0.1.13, too.

Admittedly, `.and_then()` looks kinda ugly, but with async/await soon it'll be possible to write:

```rust
let tfunc = move || {
    // test goes here
    let client = hyper::Client::new();
    let res = await!(client.get("http://www.example.com".parse().unwrap()))?;
    assert_eq!(res.status(), 200);
    Ok(())
};
```

So why was the original code working with tokio 0.1.11 but not tokio 0.1.13? The reason is that we changed how tokio interfaces with async IO:

* In 0.1.11, there was a single global reactor in a dedicated background thread. This thread is driving the reactor until the runtime is shut down. Calling `.wait()` inside a running task would simply wait until the reactor thread notifies us that the future is ready.

* In 0.1.13, we create one reactor per worker thread, and every reactor is driven only when its thread goes to sleep or switches tasks. By calling `.wait()`, we block the current worker thread and it will never get a chance to drive its reactor. Instead, we need to use `.and_then()` so that the worker thread sees the task as not ready, then goes to sleep to drive its reactor until the reactor notifies the task, and the worker thread finally continues executing the task.

I'm going to close this issue because it's not a bug. If you have any further questions, let me know!

**Closed by stjepang** 2018-12-24 14:43 UTC

**Comment by kahing** [comment] 2018-12-28 20:55
makes sense, I figured it's something like that. I suppose I will try to emulate something like the old behavior in my tests because I really prefer the ergonomics of the legacy/broken way and performance is not a concern in tests
