### ISSUE TITLE
Schedulers overeagerly polls the block_on future

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1897] opened 2019-12-04 20:39 UTC
The schedulers will currently always poll the future passed to `block_on` at the start of its tick loop, even if that future hasn't notified it is ready.

For example:

```rust
#[tokio::main]
async fn main() {
    let task = tokio::task::spawn(async {
        for _ in 0..4 {
            tokio::time::delay_for(Duration::from_millis(10)).await;
        }
    });

    task.await;
}
```

This will poll the `main` task, and then the `spawn`ed task with each loop. After parking and the clock notifies that the spawned task is ready, the loop will again poll `main` and then `spawn`, even though `main` won't be ready until the `spawn`ed task finishes and notifies.

**Comment by Darksonn** [comment] 2020-06-11 20:36
That sounds like a different issue. @MOZGIII can you open a new issue about paused time advancing unexpectedly?

**Comment by MOZGIII** [comment] 2020-06-11 21:05
https://github.com/tokio-rs/tokio/issues/2090 is already opened, honestly, I found that one first and then came here, as this is referred as a root cause for than one.

**Comment by seunghunee** [comment] 2021-12-02 12:29
#3582
I think we can close this issue.

**Closed** 2021-12-02 14:26 UTC
Labels: C-bug, E-help-wanted, A-tokio, M-runtime, E-medium
