### ISSUE TITLE
 tokio/examples/chat.rs . Demo not read message from client. 

### ISSUE THREAD

**Issue by king0bear** [tokio-rs/tokio#4813] opened 2022-07-07 03:37 UTC
Hi .
My computer is Mac M1.
first `cargo new chat `
I  clone tokio/examples/chat.rs .
I use TCP client connect to server, it is ok.
then send message using client. 
No Evnet.

`
 let username = match lines.next().await {
        Some(Ok(line)) => line,
        // We didn't get a line so we return early here.
        _ => {
            tracing::error!("Failed to get username from {}. Client disconnected.", addr);
            return Ok(());
        }
    };
`

 it is not run.

My Cargo.toml
`
[dependencies]
tracing = "0.1.26"
#provides a compatibility layer with the futures crate, allowing spans to be attached to Futures, Streams, and Executors.
#tracing-futures提供与futures crate的兼容性层，允许将跨度附加到Futures, Streams, and Executors。
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.19"
tokio = { version = "1", features = ["full","tracing"] }
tokio-stream = { version = "0.1"}
tokio-util = { version = "0.7.0",features = ["full"]}
futures = { version = "0.3.0", features = ["thread-pool"]}
`

**Comment by Noah-Kennedy** [comment] 2022-07-07 04:10
@king0bear is this a duplicate of #4812?

**Comment by Darksonn** [comment] 2022-07-09 11:30
Closing as duplicate.

**Closed by Darksonn** 2022-07-09 11:30 UTC
Labels: A-examples
