### ISSUE TITLE
LengthDelimitedCodec example not correct in Document

### ISSUE THREAD

**Issue by ygf11** [tokio-rs/tokio#4184] opened 2021-10-20 08:27 UTC
**tokio-util version**
 0.6.8.

**Platform**
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

**Description**

I find some examples in LengthDelimitedCodec seems not correct.
`First`:
https://github.com/tokio-rs/tokio/blob/44e9013f6496a806040dc04b03c8d1d9968dd809/tokio-util/src/codec/length_delimited.rs#L76-L101

I run this example, the decoded result is  `\x00 \x0B Hello wor`, which in the example should `\x00\x0B Hello world` ， the issue is that the length does not contain the length of the header, or we can just set length_adjustment.

`Second`:
https://github.com/tokio-rs/tokio/blob/44e9013f6496a806040dc04b03c8d1d9968dd809/tokio-util/src/codec/length_delimited.rs#L141-L168

My decoded result is `\x00\x0D Hello wor`, which in the example is `\x00\x0D Hello world`.

`Third`:
https://github.com/tokio-rs/tokio/blob/44e9013f6496a806040dc04b03c8d1d9968dd809/tokio-util/src/codec/length_delimited.rs#L176-L206

My decoded result  is `\x00\x00\x0B\xCA\xFE Hello wo`, which in document is `\x00\x00\x0B \xCA\xFE  Hello world`.
****

**Comment by hi-rustin** [comment] 2021-12-18 15:26
The results of my tests look as if they are correct.

My code: 
```rs
use bytes::Bytes;
use futures::SinkExt;

use tokio::fs::File;
use tokio::io::{AsyncRead, AsyncWrite};
use tokio_util::codec::{Framed, LengthDelimitedCodec};

async fn write_frame<T>(io: T) -> Result<(), Box<dyn std::error::Error>>
where
    T: AsyncRead + AsyncWrite + Unpin,
{
    let codec = LengthDelimitedCodec::builder()
        .length_field_offset(0) // default value
        .length_field_length(2)
        .length_adjustment(-2) // size of head
        .num_skip(0) // Do not strip frame header
        .new_codec();
    let mut transport = Framed::new(io, codec);
    let frame = Bytes::from("hello world");

    print!("{:?}", frame);
    transport.send(frame).await?;
    Ok(())
}

#[tokio::main]
async fn main() {
    let file = File::create("foo.txt").await.unwrap();
    write_frame(file).await.unwrap();
}

```

**Comment by matthiasdebernardini** [comment] 2022-11-12 14:55
Is this issue still open? I can't figure out what the problem is with the original issue. The docs appears to be correct, curious what the issue was.

**Comment by Darksonn** [comment] 2022-11-12 15:07
@matthiasdebernardini Not sure. Has the file changed since this issue?

**Comment by matthiasdebernardini** [comment] 2022-11-12 19:32
yes it has, `length_field_length(2)` was changed to `.length_field_type::<u16>()` in examples 1, 3 and 4. Looks like the builder API has changed since then? 

The example output from @hi-rustin outputs `b"hello world"11%` regardless if I use `length_field_length(2)` or `.length_field_type::<u16>()`                                                                                                                                                                                                                    

I'm just going through these "good first issues" so I can learn the project better.

**Comment by Darksonn** [comment] 2022-11-12 19:36
If this issue has been fixed, then we should close it.

**Closed** 2022-11-13 04:04 UTC
Labels: E-help-wanted, T-docs, E-easy, A-tokio-util, M-codec

**Comment by ygf11** [comment] 2022-11-13 04:06
Sorry for response later, I close it now.

**Comment by vnermolaev** [comment] 2023-01-25 10:55
> The results of my tests look as if they are correct.
> 
> My code:
> 
> ```rust
> use bytes::Bytes;
> use futures::SinkExt;
> 
> use tokio::fs::File;
> use tokio::io::{AsyncRead, AsyncWrite};
> use tokio_util::codec::{Framed, LengthDelimitedCodec};
> 
> async fn write_frame<T>(io: T) -> Result<(), Box<dyn std::error::Error>>
> where
>     T: AsyncRead + AsyncWrite + Unpin,
> {
>     let codec = LengthDelimitedCodec::builder()
>         .length_field_offset(0) // default value
>         .length_field_length(2)
>         .length_adjustment(-2) // size of head
>         .num_skip(0) // Do not strip frame header
>         .new_codec();
>     let mut transport = Framed::new(io, codec);
>     let frame = Bytes::from("hello world");
> 
>     print!("{:?}", frame);
>     transport.send(frame).await?;
>     Ok(())
> }
> 
> #[tokio::main]
> async fn main() {
>     let file = File::create("foo.txt").await.unwrap();
>     write_frame(file).await.unwrap();
> }
> ```

It seems that there is no method `send` in `Framed`, however, there is [`start_send`](https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html#method.start_send).
I find the docs for `start_send` a bit cryptic: before _each_ call of `start_send` one needs to call `poll_ready` until it returns a certain result. How do I need to call it? in an infinite loop? should I arrange my own delay? Why is this behaviour not hidden behind, say, `send`?

**Comment by Darksonn** [comment] 2023-01-31 10:48
> I find the docs for `start_send` a bit cryptic

The `start_send` method should only be used from poll methods. You should use the `SinkExt` methods instead if you're writing async code.
