### ISSUE TITLE
Download version 1.24.1 of tokio, run cargo test --release and get a direct error

### ISSUE THREAD

**Issue by San-greal** [tokio-rs/tokio#5365] opened 2023-01-09 02:22 UTC
**Version**
PS C:\Users\d00585364\Desktop\tokio-master> cargo tree | grep tokio
benches v0.0.0 (C:\Users\d00585364\Desktop\tokio-master\benches)
????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio)                              
    ????? tokio-macros v1.8.2 (proc-macro) (C:\Users\d00585364\Desktop\tokio-master\tokio-macros)
    ??  ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                  
    ????? tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream)            
    ??  ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                  
    ??  ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                  
    ??  ????? tokio-test v0.4.2 (C:\Users\d00585364\Desktop\tokio-master\tokio-test)             
    ??      ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)              
    ??      ????? tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream) (*)
    ??      ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)              
    ????? tokio-test v0.4.2 (C:\Users\d00585364\Desktop\tokio-master\tokio-test) (*)             
????? tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream) (*)            
????? tokio-util v0.7.4 (C:\Users\d00585364\Desktop\tokio-master\tokio-util)                     
    ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                      
    ????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                      
    ????? tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream) (*)        
    ????? tokio-test v0.4.2 (C:\Users\d00585364\Desktop\tokio-master\tokio-test) (*)             
examples v0.0.0 (C:\Users\d00585364\Desktop\tokio-master\examples)                               
????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                          
????? tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream) (*)            
????? tokio-util v0.7.4 (C:\Users\d00585364\Desktop\tokio-master\tokio-util) (*)                 
stress-test v0.1.0 (C:\Users\d00585364\Desktop\tokio-master\stress-test)                         
????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)                          
tests-build v0.1.0 (C:\Users\d00585364\Desktop\tokio-master\tests-build)                         
tests-integration v0.1.0 (C:\Users\d00585364\Desktop\tokio-master\tests-integration)             
????? tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)
tokio v1.24.1 (C:\Users\d00585364\Desktop\tokio-master\tokio) (*)
tokio-macros v1.8.2 (proc-macro) (C:\Users\d00585364\Desktop\tokio-master\tokio-macros) (*)
tokio-stream v0.1.11 (C:\Users\d00585364\Desktop\tokio-master\tokio-stream) (*)
tokio-test v0.4.2 (C:\Users\d00585364\Desktop\tokio-master\tokio-test) (*)
tokio-util v0.7.4 (C:\Users\d00585364\Desktop\tokio-master\tokio-util) (*)

**Platform**
Windows10 Intel i7-8700 CPU

**Description**
Download version 1.24.1 of tokio, run cargo test --release and get a direct error：

running 1 test
test sync_two_lit_expr_no_comma ... ok
test join_does_not_allow_tasks_to_starve ... ok
test a_different_future_is_polled_first_every_time_poll_fn_is_polled ... ok

failures:

---- join_size stdout ----
thread 'join_size' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `40`', tokio\tests\macros_join.rs:84:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by taiki-e** [comment] 2023-01-09 02:24
Duplicate of #5253.

**Closed by taiki-e** 2023-01-09 02:24 UTC
Labels: C-bug, A-tokio
