### ISSUE TITLE
BorrowMutError in tokio-0.2.4

### ISSUE THREAD

**Issue by fafhrd91** [tokio-rs/tokio#1929] opened 2019-12-09 08:31 UTC
panics in 0.2.4, worked in 0.2.2

```rust
thread 'actix-rt:worker:3' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: std::panicking::begin_panic
  14: std::panicking::begin_panic
  15: core::result::Result<T,E>::expect
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16: core::cell::RefCell<T>::borrow_mut
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/cell.rs:869
  17: actix_utils::mpsc::Receiver<T>::close
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-1.0.0-alpha.3/src/mpsc.rs:135
  18: <actix_utils::mpsc::Receiver<T> as core::ops::drop::Drop>::drop
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-1.0.0-alpha.3/src/mpsc.rs:171
  19: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  20: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  21: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  22: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  23: core::ptr::real_drop_in_place
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  24: tokio::task::core::Core<T>::transition_to_consumed
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/core.rs:106
  25: tokio::task::harness::Harness<T,S>::do_cancel::{{closure}}::{{closure}}
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:363
  26: core::ops::function::FnOnce::call_once
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  27: <getopts::OptGroup as core::clone::Clone>::clone
  28: std::panicking::try::do_call
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  30: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  31: <getopts::OptGroup as core::clone::Clone>::clone
  32: tokio::task::harness::Harness<T,S>::do_cancel::{{closure}}
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:361
  33: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/loom/std/causal_cell.rs:41
  34: tokio::task::harness::Harness<T,S>::do_cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:359
  35: tokio::task::harness::Harness<T,S>::cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:342
  36: tokio::task::raw::cancel
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:196
  37: tokio::task::raw::RawTask::cancel_from_queue
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/raw.rs:145
  38: tokio::task::Task<S>::shutdown
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/mod.rs:385
  39: tokio::task::queue::RemoteQueue<S>::schedule
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/queue.rs:307
  40: <tokio::task::local::Scheduler as tokio::task::Schedule>::schedule
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/local.rs:348
  41: tokio::task::harness::Harness<T,S>::wake_by_ref
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:315
  42: tokio::task::harness::Harness<T,S>::wake_by_val
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/harness.rs:299
  43: tokio::task::waker::wake_by_val
             at /Users/fafhrd91/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/task/waker.rs:84
  44: core::task::wake::Waker::wake
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/task/wake.rs:252
```

**Comment by carllerche** [comment] 2019-12-09 15:58
Do you have some sort of repro? It looks like the borrow error is coming from user code? There were bugs fixed in 0.2.3 related to LocalSet, so we would need a bit more info to go off of.

**Comment by carllerche** [comment] 2019-12-09 16:00
Are you perhaps holding on to a ref cell borrow across an await?

**Comment by fafhrd91** [comment] 2019-12-09 16:16
i have code that notify waker in drop. it doesnt have access to localset, just waker. this happens on shutdown. i updated stack trace. i think this problem in both 0.2.4 and 0.2.3

**Comment by carllerche** [comment] 2019-12-09 16:59
I think I *might* see what is going on, but I'm not 100% sure. Is there more stack trace?  What is calling `wake`?

**Comment by carllerche** [comment] 2019-12-09 17:06
My guess is somehow the `LocalSet` is being dropped while, at the same time, a task is being woken. The issue appears that `drop` is called on the task "inline" which causes the conflict between waking the task and dropping (borrow error).

I'm just not sure how to get into that path. Seeing what calls wake would be helpful.

**Comment by carllerche** [comment] 2019-12-09 17:08
It *looks* like it is the same bug as #1886, but we have not personally been able to reproduce, so any help would be appreciated.

**Comment by hawkw** [comment] 2019-12-09 20:35
@fafhrd91 are you able to share code that causes this panic?

**Comment by fafhrd91** [comment] 2019-12-10 00:21
I’ll try to create reproducible example

**Comment by carllerche** [comment] 2019-12-14 03:25
As an update. I am pretty sure that I found the issue and am working on a fix. It’s taking a bit of rejiggering in the shutdown process details so I want to make sure the changes are correct. I should have a fix out within a few days (weekend unfortunately)

**Comment by carllerche** [comment] 2019-12-17 17:52
If you are able to, are you able to check if #1972 fixes your issue?

**Comment by fafhrd91** [comment] 2019-12-18 03:28
#1972 fixes the problem. thanks

**Comment by carllerche** [comment] 2019-12-18 04:02
Thanks for confirming. I will publish a release tomorrow.

**Closed** 2019-12-18 04:52 UTC
Labels: bug
