### ISSUE TITLE
examples/chat-combinator.rs does not react to clients connecting in tokio-0.1.1

### ISSUE THREAD

**Issue by lu-zero** [tokio-rs/tokio#191] opened 2018-03-07 20:08 UTC
Testing the same code in the same way (using `cargo run --example connect 127.0.0.1:8080`) does not produce any effect.

It works as intended on the current git.

**Comment by kpp** [comment] 2018-03-08 20:21
Your servers and clients does not match each other.

```
$ head -n 15 tokio/examples/echo.rs 
//! A "hello world" echo server with tokio-core
//!
//! This server will create a TCP listener, accept connections in a loop, and
//! simply write back everything that's read off of each TCP connection. Each
//! TCP connection is processed concurrently with all other TCP connections, and
//! each connection will have its own buffer that it's reading in/out of.
//!
//! To see this server in action, you can run this in one terminal:
//!
//!     cargo run --example echo
//!
//! and in another terminal you can run:
//!
//!     cargo run --example connect 127.0.0.1:8080
//!
```

**Comment by lu-zero** [comment] 2018-03-08 21:00
Not sure how what you pasted is related?

It refers to `chat` and not `chat-combinator` but, as said beside that nit I can connect the clients but they do not interact beside that.
 
```
//! A chat server that broadcasts a message to all connections.
//!
//! This is a simple line-based server which accepts connections, reads lines
//! from those connections, and broadcasts the lines to all other connected
//! clients. In a sense this is a bit of a "poor man's chat server".
//!
//! You can test this out by running:
//!
//!     cargo run --example chat
//!
//! And then in another window run:
//!
//!     cargo run --example connect 127.0.0.1:8080
//!
//! You can run the second command in multiple windows and then chat between the
//! two, seeing the messages from the other client as they're received. For all
//! connected clients they'll all join the same room and see everyone else's
//! messages.
```

**Comment by carllerche** [comment] 2018-03-08 21:19
@lu-zero Could you provide more details about how to reproduce?

I checked out Tokio at the `tokio-0.1.1` tag and ran both examples (chat-combinator and connect) but I saw the connection be established.

**Comment by lu-zero** [comment] 2018-03-08 21:22
Connect two clients.
The connection establishes, but if you send messages it does not appear on the other client.

I can switch back to tokio-0.1.1 and test again in minutes.

**Comment by kpp** [comment] 2018-03-08 21:30
The first terminal:
```
$ cargo run --example chat-combinator 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/chat-combinator`
Listening on: 127.0.0.1:8080
// The second terminal called cargo run --example connect 127.0.0.1:8080
New Connection: 127.0.0.1:32936
```

**Comment by kpp** [comment] 2018-03-08 21:32
The first terminal:
```
$ cargo run --example chat
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/chat`
server running on localhost:6142
`b"123"` is joining the chat
Received line (b"123") : Some(b"asdasd")
Received line (b"123") : Some(b"qweqweqweqweqw")
Received line (b"123") : Some(b"\x04\xff\xf4\xff\xfd\x06")
Received line (b"123") : Some(b"\x1b")
Received line (b"123") : None
^C
```

The second terminal:
```
$ telnet localhost 6142
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
123
asdasd
qweqweqweqweqw
^C
^[
^]
telnet> Connection closed.
```

**Comment by carllerche** [comment] 2018-03-08 21:38
I looked at the diff between the two examples. The code has been rewritten since 0.1.1 and I think it just happened to be broken in 0.1.1 and has since been fixed.

So, I'm going to close the issue as "fixed on master" :) Thanks for investigating!

**Closed by carllerche** 2018-03-08 21:38 UTC
