### ISSUE TITLE
Future's destructor not getting called, correlated with receiver not getting items after 0.2 -> 0.3 upgrade

### ISSUE THREAD

**Issue by tbraun96** [tokio-rs/tokio#3213] opened 2020-12-04 14:08 UTC
**Version**
0.3.5 (using rust nightly)
**Platform**
Windows 10, Ubuntu Linux

**Description**
Ever since Upgrading my code from tokio 0.2 to 0.3, I'm getting a strange bug. The receiver does not detect any items in its channel, despite sending a value to it (which, according to the sending side, returned an Ok(()) result). I had to expand my code into more steps to find what may be happening. What I discovered, by using printlns!() in the tokio source code, is that the destructor for tokio::time::sleep()'s abstraction does not get called, yet, the loop continues

```rust
    async fn outbound_stream<S: SinkExt<Bytes> + Unpin>(mut primary_outbound_rx: tokio::sync::mpsc::UnboundedReceiver<Bytes>, mut writer: S) -> Result<(), NetworkError> {
        log::info!("Executing outbound stream");

        loop {
            log::info!("LOOP");
            match primary_outbound_rx.try_recv() {
                Ok(outbound_packet) => {
                    log::info!("outbound_stream sending object w/ {} bytes to TCP stream (using LengthDelimitedCodec)", outbound_packet.len());
                    if let Err(err) = writer.send(outbound_packet).map_err(|_| NetworkError::InternalError("Writer stream corrupted")).await {
                        log::error!("Err: {:?}", &err);
                        return Err(err);
                    }
                }

                Err(err) => {
                    log::error!("TryRecvError ({})", err.to_string());
                }
            }
           
            // we get here, but no further per loop. I'm using an arbitrary sleep here to see what may be affecting the code
            tokio::time::sleep(Duration::from_millis(500)).await;
            // We DON'T make it this far. After editing the source code for tokio's abstraction returned from sleep(), I noticed
            // that drop does NOT get called. Despite this, the loop continues but never makes it here
            log::info!("Done sleep!");
        }
        Ok(())
    }
```

This bug did not happen in tokio 0.2. Also, this entire function is put inside a ``FuturesUnordered`` along with other futures. That combined future does not end, and this function does not end. As the code implies, it keeps looping, but never making it past ``tokio::time::sleep()``. Also, very strangely, by adding printlns! inside the ``poll`` function under ``impl Future for Sleep`` to track the internal state, it returns ``Poll::Ok(())``, yet, the destructor does not get called. The error must be somewhere inside tokio's reactor?

Note: normally, I don't use sleep in my code. This was added just to debug the original while-let loop that pulled values from the receiver's stream, allowing some rest between each iteration of the loop. In doing this, I found that the destructor wasn't being called, which may be related to the receiver not detecting any items

I have tried executing this code in a ``LocalSet`` and multi-threaded context, but the result doesn't change.

The first item does get received and works as expected. However, the second and every following item sent to the receiver does not get recognized.

**Comment by Darksonn** [comment] 2020-12-04 15:44
It's unclear what exactly the issue is. Can you post a full example that I can run on my own to see the issue?

**Comment by codeflo** [comment] 2020-12-20 07:11
@tbraun96 Did you find anything? I’m also having trouble with an mpsc channel not receiving any items after upgrading to 0.3 with no other change. I wonder if it’s the same bug, but I don’t have a small example yet.

**Comment by Darksonn** [comment] 2020-12-20 09:12
I'm closing this as, after having discussed with Thomas on the user's forum, it's unclear what is wrong and no reproducible example has been provided.

@codeflo This has nothing to do with mpsc channels. If anything, it was something with timers. In any case, if you have trouble with using the mpsc channels, please open a new issue or [discussion](https://github.com/tokio-rs/tokio/discussions).

**Closed by Darksonn** 2020-12-20 09:12 UTC
Labels: A-tokio, C-bug

**Comment by codeflo** [comment] 2020-12-20 14:14
@Darksonn Closing a bug after not receiving any clarification for two weeks is completely fair of course.

But just to explain why I asked: After reading @tbraun96's carefully, I noticed that it was a channel issue that *originally* led them down this path of investigation. The sleep thing was only something they noticed while debugging the original problem.

Since I'm also convinced that there's been a change of behavior *somewhere* in the stack with the update, I was hoping that we might get to the bottom of this with combined forces. To be clear, I don't even know yet if there's a bug in Tokio, it's entirely possible that an existing bug in *my* code is only now being triggered.

In any case, I'll do some more investigating. Thanks for the pointer to the discussion forum.

**Comment by tbraun96** [comment] 2020-12-20 14:18
@codeflo says: "The sleep thing was only something they noticed while debugging the original problem"

Yes, this is true. This was a symptom of the problem, kind of like how coughing can be the symptom of the flu. The receiver not getting values is another symptom, but is closer to the source of the problem. Finding "the flu" is the goal here

**Comment by tbraun96** [comment] 2020-12-20 14:22
@codeflo, I have spent considerable time trying to find the problem, but eventually had to shelf the update and continue using tokio 0.2. However, going over this again, perhaps we can figure out the problem. In your codebase, do you explicitly use Wakers? I know I do, and heard from @Darksonn that intrusive wakers are being used in 0.3. If you don't then explicit waker use is not the problem, and we can cross that off the list

**Comment by tbraun96** [comment] 2020-12-20 14:24
Our goal is to figure out something we both do in our code that could be leading to this issue, because apparently, others aren't having this issue

**Comment by codeflo** [comment] 2020-12-21 08:43
I don't explicitly use wakers, but that idea led me to where the problem was: custom implementations of complicated traits. Maybe the commonality is just that we both have implemented for some Tokio traits, and didn't always get it exactly right. ;)

Here's what it was for me: I had my own implementation of tokio_util::codec::Decoder for custom deserialization. I didn't handle None values correctly, but the old implementation of UdpFramed never triggered that bug. Unfortunately for me, UdpFramed was rewritten and now requires a more complete Decoder implementation. I only implicated the mpsc channel because that's where I first observed my problem, further down the processing pipeline. But as you suggested, that was the symptom, not the cause.

It's unlikely that you did exactly the same thing, so sorry if I can't help. Is it possible that somewhere else in your code, you crash/panic a worker thread, which might cause some tasks to be lost and never executed? That's only a wild guess, I don't know enough about Tokio's runtime to tell if that's a possibility. In any case, good look with the bug hunt! And thanks for the idea that led me to the solution! :)

**Comment by Darksonn** [comment] 2020-12-21 09:19
> Is it possible that somewhere else in your code, you crash/panic a worker thread, which might cause some tasks to be lost and never executed? 

If a task panics, that impacts only that task. The worker thread it was on will catch the panic and correctly continue to execute other tasks.

**Comment by tbraun96** [comment] 2021-02-09 01:13
In case I find a solution in the future, I will continue to write updates here to keep track as things change:

The error seems to persist, but in a different form for tokio version 1.2. ``tokio::task::spawn`` and ``tokio::task::spawn_local`` don't seem to be spawning tasks unless I ``.await`` the ``JoinHandle``

**Comment by Darksonn** [comment] 2021-02-09 10:17
Every time I have heard that description, it has been because you have been [blocking the thread](https://ryhl.io/blog/async-what-is-blocking/), stopping Tokio from swapping one of the threads to work on the new task.

**Comment by tbraun96** [comment] 2021-02-09 13:20
I've begun to suspect this, however, it's difficult to accept because the code runs perfectly on tokio 0.2. Maybe there was an internal tokio change that prompted my design to be rendered as blocking-like after using 0.2. I will search for any places where blocking may occur (or, if any other bug occurs) and will report back when I find the issue.

Note: My project forbids unsafe code, so no holding sync rwlocks/mutexes across ``.await`` waypoints

**Comment by Darksonn** [comment] 2021-02-09 14:00
One place that sometimes have caught people off guard is the fact that `TcpStream::from_std` no longer sets the socket to non-blocking mode automatically. Maybe that's it?

**Comment by tbraun96** [comment] 2021-02-09 14:17
AFTER OVER 40 HOURS OF LOOKING FOR THE PROBLEM, YOU SOLVED IT! Yes, I was using net2 to construct custom opts for the ``TcpListener``'s and ``TcpStreams``. I didn't set ``nonblocking`` to true, but once I did, it worked!
