### ISSUE TITLE
tokio@0.2.14 + futures::executor::block_on causes hang

### ISSUE THREAD

**Issue by bryanburgers** [tokio-rs/tokio#2376] opened 2020-04-03 20:55 UTC
## Version

`tokio@0.2.14` and `tokio@0.2.15` exhibit this issue, `tokio@0.2.13` does not.

```
tokio-hang-reproduction v0.1.0 (/Users/bryan/personal/tokio-hang-reproduction)
│   │   │   ├── tokio v0.2.14
│   │   │   │   └── tokio-macros v0.2.5
│   │   │   └── tokio-util v0.3.1
│   │   │       └── tokio v0.2.14 (*)
│   │   ├── tokio v0.2.14 (*)
│   ├── tokio v0.2.14 (*)
└── tokio v0.2.14 (*)
```

## Platform

Currently, I can get this to happen on AWS Lambda.

I can not reproduce on MacOS (`Darwin Bryans-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`) or in Docker-for-Mac.

## Description

For our GraphQL server, we use AWS Lambda + Juniper + Tokio. Juniper is currently a synchronous library, but the Lambda library we use and our model layer are fully tokio@0.2.

In order to get Juniper to call our models, we use `futures::executor::block_on`, based largely on this comment: https://github.com/tokio-rs/tokio/issues/2042#issuecomment-569919258

Starting with tokio@0.2.14, this approach has started hanging and causing timeouts. Downgrading to tokio@0.2.13 solved the issue.

https://github.com/bryanburgers/tokio-hang-reproduction

```rust
#![allow(dead_code)]
use futures::stream::{self, StreamExt};
use tokio::time::delay_for;
use std::time::Duration;
use serde_json::{Value, json};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    let fun = lambda::handler_fn(handler);
    lambda::run(fun).await?;
    Ok(())
}

async fn handler(_event: Value) -> Result<Value, String> {
    let result = invoke_juniper();
    // If we don't use juniper and .await the futures normally, it works fine.
    // let result = test1(100).await;
    println!("result={:?}", result);
    Ok(json!({}))
}

// Juniper (https://crates.io/crates/juniper) is a synchronous library.
fn invoke_juniper() -> Vec<usize> {
    // And from it, we call into our async code using block_on
    futures::executor::block_on(test1(100))
}


// All three of these functions fail after executing ~60 futures.
async fn test1(n: usize) -> Vec<usize> {
    stream::iter(0..n).map(pause_and_return).buffer_unordered(10).collect().await
}

async fn test2(n: usize) -> Vec<usize> {
    stream::iter(0..n).map(pause_and_return).buffered(10).collect().await
}

async fn test3(n: usize) -> Vec<usize> {
    let mut vec = Vec::new();
    for i in 0..n {
        vec.push(pause_and_return(i).await);
    }
    vec
}

async fn pause_and_return(n: usize) -> usize {
    println!("Starting {}", n);
    delay_for(Duration::from_millis(100)).await;
    println!("Finished {}", n);
    n
}
```

**Comment by bryanburgers** [comment] 2020-04-03 20:56
A coworker was just able to reproduce this on Linux without requiring Lambda.

```
Linux some.hostname 4.15.0-1060-aws #62-Ubuntu SMP Tue Feb 11 21:23:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jatsrt** [comment] 2020-04-03 20:57
To run it without lambda:
```rust
#![allow(dead_code)]
use futures::stream::{self, StreamExt};
use tokio::time::delay_for;
use std::time::Duration;
use serde_json::{Value, json};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    handler(Value::Null).await?;
    Ok(())
}

async fn handler(_event: Value) -> Result<Value, String> {
    let result = invoke_juniper();
    // If we don't use juniper and .await the futures normally, it works fine.
    // let result = test1(100).await;
    println!("result={:?}", result);
    Ok(json!({}))
}

// Juniper (https://crates.io/crates/juniper) is a synchronous library.
fn invoke_juniper() -> Vec<usize> {
    // And from it, we call into our async code using block_on
    futures::executor::block_on(test1(100))
}


// All three of these functions fail after executing ~60 futures.
async fn test1(n: usize) -> Vec<usize> {
    stream::iter(0..n).map(pause_and_return).buffer_unordered(10).collect().await
}

async fn test2(n: usize) -> Vec<usize> {
    stream::iter(0..n).map(pause_and_return).buffered(10).collect().await
}

async fn test3(n: usize) -> Vec<usize> {
    let mut vec = Vec::new();
    for i in 0..n {
        vec.push(pause_and_return(i).await);
    }
    vec
}

async fn pause_and_return(n: usize) -> usize {
    println!("Starting {}", n);
    delay_for(Duration::from_millis(100)).await;
    println!("Finished {}", n);
    n
}
```

**Comment by hawkw** [comment] 2020-04-03 21:02
What happens if you put the blocking call (`invoke_juniper`) in a `tokio::task::spawn_blocking` or `tokio::task::block_in_place` call?

**Comment by bryanburgers** [comment] 2020-04-03 21:09
Quickly testing with `spawn_blocking` does seem to work on tokio@0.2.14 and tokio@0.2.15, on Lambda.

```rust
async fn handler(_event: Value) -> Result<Value, String> {
    let result = tokio::task::spawn_blocking(invoke_juniper).await.map_err(|e| e.to_string())?;
    println!("result={:?}", result);
    Ok(json!({}))
}
```

Great! Thank you, @hawkw!

Can you help me understand why this helps? And if this is a long-term fix or a short-term fix?

I know [you had mentioned previously](https://github.com/tokio-rs/tokio-compat/issues/23#issuecomment-573232615) that using `futures::executor::block_on` isn't ideal, but at the time there didn't seem to be a better way. I'm curious if there's a better way now?

**Comment by hawkw** [comment] 2020-04-03 21:31
So, the code inside the `futures::executor::block_on` is not _really_ running on the tokio executor. If a future inside of the `block_on` yields, it only yields to the executor created by the call to `block_on`, _not_ back to the Tokio runtime created by `tokio::main`. 

I think that the reason this code is breaking in 0.2.14 is because 0.2.14 introduced [automatic cooperative task yielding](https://tokio.rs/blog/2020-04-preemption/) to improve the scheduler's fairness. After your stream iterates so many times, in 0.2.14+ the task's budget is exhausted, and it yields to the executor to give other tasks a turn. When that happens, it _should_ notify itself so that it goes to the end of the queue to continue executing after other tasks have been allowed to run. go to the end of the queue to be notified again. My guess is that for some reason related to an interaction between `futures::executor::block_on` and running on a Tokio worker, your task is not being polled again after it yields.

Using `spawn_blocking` fixes this, because the blocking code is now running on a separate blocking threadpool, rather than on a Tokio worker thread. However, it's not ideal, because when you use `block_on` to start executing async code again, it's no longer running on the Tokio runtime. I think what you want to be doing is running the blocking call with `spawn_blocking`, and when you need to call back into your async code, you spawn it on the main Tokio runtime, and only use `futures::executor::block_on` (from the blocking thread) to await the spawned future's `JoinHandle`. I mean, ideally, you wouldn't be doing _that_, either --- the blocking code would just return, and then the async work would continue, rather than having the blocking code call back into asynchronous code, but if the third-party library doesn't work that way, I guess this would be the closest you can get.

**Comment by carllerche** [comment] 2020-04-03 21:55
Calling `futures::executor::block_on(...)` should never be done from within the context of a tokio task. Unfortunately, we do not control that function as it is from `futures`. If we did, we would make it panic.

The solution is indeed to wrap blocking calls w/ `spawn_blocking`.

**Comment by bryanburgers** [comment] 2020-04-04 02:14
I understand that I shouldn’t be using `futures::executor::block_on`.

I understand that `spawn_blocking` can get me from an async context to a sync context so I can call the third party code (in this case, Juniper).

What I don’t understand is when Juniper calls code I provided to it (assuming a synchronous context), how can I get back into an async context to get data that I can return to it Juniper?

That’s why `futures::executor::block_on` is appealing (even though it’s wrong). It has the right signature.

I need something that is roughly `fn _(fut: impl Future<Output=T>) -> T`.

I can’t use `runtime.block_on` because In this context it’s not possible to have a mutable reference to the runtime. `Handle` doesn’t have a `block_on`. If the `JoinHandle` returned from a `handle.spawn` can be waited for from a synchronous context, I don’t see it.

I really wish I didn’t have to do the async -> sync -> async dance, but at this point I don’t have a choice. I’m really looking for _any_ reliable way to make that second jump.

**Comment by carllerche** [comment] 2020-04-04 02:35
Use `spawn_blocking` when you go from async -> sync. If you do that, you 100% can use `futures::executors::block_on` to go from sync -> async.

**Comment by hawkw** [comment] 2020-04-04 03:46
> I can’t use `runtime.block_on` because In this context it’s not possible to have a mutable reference to the runtime. `Handle` doesn’t have a `block_on`. If the `JoinHandle` returned from a `handle.spawn` can be waited for from a synchronous context, I don’t see it.

What I was trying to suggest is just that (IMO) you would probably prefer your async code in the callback to be running on the tokio executor alongside your other async code, rather than on the separate executor created by `block_on`. So, if you use `spawn_blocking` to go from async to sync, you would want to use `futures::executor::block_on` with a `JoinHandle` rather than passing your future into `block_on` directly.

**Comment by bartlomieju** [comment] 2020-04-07 11:22
We're experiencing the same problem in Deno - after flushing a few string to stdout executor hangs. Similar to @bryanburgers we use `future::executor::block_on()` to block current thread on the write future. 

Contrary to @carllerche [advice](https://github.com/tokio-rs/tokio/issues/2376#issuecomment-608705523) we issue a call `block_on()` from context of Tokio task:

https://github.com/denoland/deno/blob/e586d0c8b813c276cd5a1ba30582022b3c2be2eb/cli/ops/dispatch_minimal.rs#L114-L166

(problematic bit is at the end of function)

`spawn_blocking` and `block_in_place` are not really viable solutions in this case because we use single threaded Tokio runtime and futures are not marked as `Send`. Is there a way to manually reset task budget or ignore budget altogether?

**Comment by Darksonn** [comment] 2020-04-07 12:59
@bartlomieju  Using `block_on` in a single-threaded executor sounds like a recipe for deadlock disaster. I very strongly recommend finding another solution.

**Closed** 2022-06-16 07:58 UTC
Labels: C-question, A-tokio, I-hang

**Comment by ntc2** [comment] 2024-09-12 15:17
I also ran into this problem with `futures::executor::block_on` causing hangs in tokio 1.40.0. I was able to solve the problem by wrapping in `tokio::task::spawn_blocking` as suggested in https://github.com/tokio-rs/tokio/issues/2376#issuecomment-608959390, and it seems that creating a new tokio runtime and `enter`ing it also works (see the `main3` functions below). The problem doesn't depend on whether the runtime is single or multi threaded.

Here is a super simple reproduction of the problem:

```rust
// Hang after printing 128.
//
// A sync function that calls `sync_fn` many times.
#[tokio::main]
async fn main() {
    for i in 0..1000 {
        println!("{i}");
        sync_fn();
    }
}

// A sync function that blocks on an async function that needs a tokio
// runtime.
fn sync_fn() {
    futures::executor::block_on(async { async_fn().await });
}

// An async function that needs a tokio runtime.
async fn async_fn() {
    tokio::task::spawn_blocking(|| ()).await.unwrap();
}
```

Below are various failures and successes, including the error messages, in case this will help other people Googling this problem (it took me a while to find this ticket and realize I was experiencing the same problem).

First using `futures::executor::block_on` to call async code from sync code:
<details>


```rust
// Use futures::executor::block_on to run the async function synchronously.
#[cfg(test)]
mod example_futures {
    // Panic: "there is no reactor running, must be called from the context of a
    // Tokio 1.x runtime".
    #[test]
    fn main0() {
        main();
    }

    // Hang after printing 128.
    #[tokio::test(flavor = "multi_thread")]
    async fn main1() {
        main();
    }

    // Success.
    #[tokio::test(flavor = "multi_thread")]
    async fn main2() {
        tokio::task::spawn_blocking(main).await.unwrap();
    }

    // Success.
    #[test]
    fn main3() {
        let rt = tokio::runtime::Runtime::new().unwrap();
        let _guard = rt.enter();
        main();
    }

    // A sync function that calls `sync_fn` many times.
    fn main() {
        for i in 0..1000 {
            println!("{i}");
            sync_fn();
        }
    }

    // A sync function that blocks on an async function that needs a tokio
    // runtime.
    fn sync_fn() {
        futures::executor::block_on(async { async_fn().await });
    }

    // An async function that needs a tokio runtime.
    async fn async_fn() {
        tokio::task::spawn_blocking(|| ()).await.unwrap();
    }
}
```
</details>

Second using `tokio::runtime::Handle::current()` to call async code from sync code:
<details>

```rust

// Use tokio::runtime::Runtime::block_on to run the async function synchronously.
#[cfg(test)]
mod example_tokio {
    // Panic: "there is no reactor running, must be called from the context of a
    // Tokio 1.x runtime".
    #[test]
    fn main0() {
        main();
    }

    // Panic: "Cannot start a runtime from within a runtime. This happens because
    // a function (like `block_on`) attempted to block the current thread while
    // the thread is being used to drive asynchronous tasks."
    #[tokio::test(flavor = "multi_thread")]
    async fn main1() {
        main();
    }

    // Success.
    #[tokio::test(flavor = "multi_thread")]
    async fn main2() {
        tokio::task::spawn_blocking(main).await.unwrap();
    }

    // Success.
    #[test]
    fn main3() {
        let rt = tokio::runtime::Runtime::new().unwrap();
        let _guard = rt.enter();
        main();
    }

    // A sync function that calls `sync_fn` many times.
    fn main() {
        for i in 0..1000 {
            println!("{i}");
            sync_fn();
        }
    }

    // A sync function that blocks on an async function that needs a tokio
    // runtime.
    fn sync_fn() {
        tokio::runtime::Handle::current().block_on(async { async_fn().await });
    }

    // An async function that needs a tokio runtime.
    async fn async_fn() {
        tokio::task::spawn_blocking(|| ()).await.unwrap();
    }
}
```
</details>

**Comment by Darksonn** [comment] 2024-09-13 07:14
@ntc2 It's completely expected that this will not work. Using `block_on` from within Tokio is a really bad idea. Tokio's own `block_on` will panic if you try to prevent such bugs, but there's nothing Tokio can do if you use `futures::executor::block_on`.

**Comment by ntc2** [comment] 2024-09-14 13:52
> @ntc2 It's completely expected that this will not work. Using `block_on` from within Tokio is a really bad idea. Tokio's own `block_on` will panic if you try to prevent such bugs, but there's nothing Tokio can do if you use `futures::executor::block_on`.

@Darksonn yes, understood, you guys have made that clear in the comments here :) However, given that there are 15 public issues linking to this issue, misusing `futures::executor::block_on` in this way seems to be a common problem. The point of my [previous comment](https://github.com/tokio-rs/tokio/issues/2376#issuecomment-2346586437) was not to suggest it should work, just to help other people like myself that make this mistake, by giving a minimal reproduction of the problem, and explaining various workarounds.

**Comment by SteveLauC** [comment] 2024-10-23 11:10
> Using `block_on` in a single-threaded executor sounds like a recipe for deadlock disaster. I very strongly recommend finding another solution.

Hi @Darksonn, would you like to explain why deadlock could happen? What I understand is, using `futures::executor::block_on()` will block the underlying runtime thread for a period of time, but it should not lead to a deadlock, thanks!

**Comment by Darksonn** [comment] 2024-10-23 11:15
Blocking the underlying runtime thread is allowed to cause a deadlock. Don't do it.

One cause can be the cooperative scheduling feature. If Tokio decides that the task has been running for too long, it will make all futures in the task return pending until the task yields back to the Tokio runtime. Another cause could be if you request a task dump.

Additional sources of deadlocks may be added in future Tokio releases. So don't do it, even if it works today.

**Comment by SteveLauC** [comment] 2024-10-23 11:19
Get it, appreciate the quick response!
