### ISSUE TITLE
Runtime::shutdown_now does nothing after futures have been spawned

### ISSUE THREAD

**Issue by PvdBerg1998** [tokio-rs/tokio#837] opened 2019-01-07 16:04 UTC
## Version

- tokio 0.1.14 (latest)

## Platform

Windows 10 64 bit

## Subcrates

Possibly `tokio_threadpool`

## Description

I have a runtime with several indefinitely running futures on it. To exit the runtime, I have one global static `Runtime` struct which I use to spawn futures on. When it's time to exit, I access the static runtime and call `runtime.shutdown_now().wait()`.

I would expect this to shutdown the runtime, but it just seems to hang forever. Perhaps I'm doing something wrong. Thanks in advance!

**Comment by PvdBerg1998** [comment] 2019-01-07 19:55
I'm using futures 0.3 with async await. I'm pretty sure it has something to do with the `loop` I used inside the `async` block. I think this loop actually loops on the executing thread and therefore will never let the runtime exit.

I've had a lot of problems trying to solve this. If someone has any idea, please let me know.

**Comment by davidbarsky** [comment] 2019-01-07 20:48
Hi @PvdBerg1998! This isn't a lot of information for us to go off of. Can you share a minimal reproduction of the problematic code and what you're trying to accomplish? Additionally, can you let us know you hope you accomplish with the loop inside of the async block?

**Comment by PvdBerg1998** [comment] 2019-01-07 21:34
I need to do a bit more testing. My guess is that it has to do with how a `loop` in an async context is converted by rustc, which is not very documented at the moment so to speak.

When I have the time I'll give an update.

**Comment by PvdBerg1998** [comment] 2019-01-07 21:44
If you want to give it a try: I think you should be able to reproduce this behavior by launching a `async { loop { await!(xyz); } }` and trying to kill the runtime.

**Comment by davidbarsky** [comment] 2019-01-07 21:49
With that code sample, you're never actually breaking out of the loop (e.g. https://doc.rust-lang.org/1.7.0/book/loops.html). Can you try breaking after the `await!`? I suspect that's what's causing your issues there.

**Comment by LucioFranco** [comment] 2019-01-07 22:07
I don't think it matters since the async block that surrounds the loop should get canceled. I would verify that the shutdown_now gets called. I have similar code in one of my projects with futures 0.3 and it seems to work. Though more code would be helpful since its a bit hard to debug without seeing context 😄

**Comment by PvdBerg1998** [comment] 2019-01-11 13:44
I'm pretty sure it's because the loop does not get transformed into a state machine. @LucioFranco that is what I expected to happen, but it does not. It appears to generate code that runs the loop during the `.poll()`.

I changed my code to something like this:
```rust
let mut x = Ok(());
while x.is_ok() {
  x = await!(xyz);
}
panic!("Error: {}", x.unwrap_err());
```

... which does actually stop when I request the runtime to stop.

**Comment by PvdBerg1998** [comment] 2019-01-11 13:46
Maybe a person with more knowledge of the current async transform should have a look at this. What would be the desired behavior? I understand the loop not being transformed to a state machine. This would not always be useful in async context. I think it should whenever there is any `await` inside the loop.

**Comment by LucioFranco** [comment] 2019-01-11 16:47
Interesting so this seems like this is more of a rust generator issue than specific with tokio. I think it would be worthwhile to open an issue there. Tokio technically does not officially support async/await, we only guarantee that stable works and that means only futures 0.1. I would suggest also possibly going to the rust-lang discord there are a few channels with the net-wg team and net-wg-async and Im sure they would know way more about this than we would 😄 .

I am going to go ahead and close this issue, if we are able to reproduce this with a futures 0.1 example then we can reopen this.

**Closed by LucioFranco** 2019-01-11 16:47 UTC
