### ISSUE TITLE
Unnotified tasks are silently dropped

### ISSUE THREAD

**Issue by Ereski** [tokio-rs/tokio#303] opened 2018-04-06 22:19 UTC
I have a future that take items from a futures::sync::mpsc channel, do some processing, and pipe the results to a tokio::net::TcpStream, with flushes at key points. The problem was that the future was being dropped by tokio right after the flush (thus causing an unrelated error due to the Receiver being closed) even though `poll()` was returning `Ok(Async::NotReady)`.

The problem was that I needed to notify the task after the flush and thus the task would never resume. While it makes sense to drop those kinds of zombie tasks, it is very counteintuitive and also undocumented (AFAIK). There is no comment even hinting at that near the function that drops the task: https://github.com/tokio-rs/tokio/blob/tokio-threadpool-0.1.2/tokio-threadpool/src/worker.rs#L305-L345

I'd like to suggest a three possible changes:
- Change the behaviour to the more intuitive "never run the task again but don't drop it".
- Print a warning if a task is being dropped for this reason.
- Document this behaviour.

**Comment by Ereski** [comment] 2018-04-08 18:36
Seems like this is not the default behaviour but a legitimate bug? I just found an instance where the future hangs instead of being dropped, as expected.

**Comment by carllerche** [comment] 2018-04-10 20:32
If a future gets into the situation where it can never run again (hang), it should be dropped. This is the expected behavior.

Adding documentation and a warning would be positive changes.

If you found a situation in which this does not happen, either there is an outstanding notify handle **somewhere**, which means the task could complete, or there is a bug.

**Comment by alxhub** [comment] 2018-09-28 15:07
I just encountered this issue last night, and pulled my hair out for an hour trying to figure out why my channels were closing all of a sudden. It ended up being because I `poll()`'d an `mpsc` channel, handled the message, and returned `NotReady` without polling the channel again.

A note in the "Returning NotReady" section of https://tokio.rs/docs/getting-started/futures/ about this behavior would have gone a long way towards making this behavior less confusing. My natural expectation was that this mistake would cause a task to hang forever, not be dropped.

**Comment by carllerche** [comment] 2018-09-28 16:14
@alxhub would you mind submitting a PR to the website repo with the change that you had in mind.

**Comment by carllerche** [comment] 2019-06-24 17:49
Closing due to inactivity. However, I think this case would be good to try to catch and log / warn somehow with tokio-trace. Thoughts @hawkw?

**Closed by carllerche** 2019-06-24 17:49 UTC
Labels: docs, help wanted, tokio-threadpool
